[tool.poetry]
name = "dsstore"
version = "0.5.9"
description = "dsstore is a wrapper package around MLflow, designed to streamline the saving, listing, and loading of data science artifacts within a project, notebooks, or apps. This package simplifies the management of various data science outputs, making it easier for users to store and retrieve models, datasets, and other essential artifacts efficiently."
authors = ["lakshman.v <lakshman.v@mathco.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
pandas = "1.5.3"
numpy = "1.24.2"
plotly = "^5.8.0"
joblib = "^1.4.2"
xgboost = "^2.1.1"
scikit-learn = "^1.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
