summary: "Change the password"
tags:
  - platform/Users
description: "User can change the password by using forgot password feature"
produces:
- "application/json"
security:
  - Authorization: []

requestBody:
  required: true
  content:
    application/json:
      schema:
        required: [email, passowrd, confirm_password]
        properties:
          email:
            type: "string"
            required: true
          password:
            type: "string"
            required: true
          confirm_password:
            type: "string"
            required: true
        example: {"email":"testuser@test.com" ,"password": "test@123#", "confirm_password": "test@123#"}
parameters:
- in: header
  name: password_token
  schema:
    scheme: "bearer"
    required: true

responses:
  200:
    description: "Success"
    schema:
      type: "object"
      example : {
        "message": "Password updated successfully"
      }

  400:
    description: "Insufficient details"
    schema:
      type: "object"
      example: {
        "message": "Insufficient details provided"
      }

  404:
    description: "Passowrd mismatch or User does not exist"
    schema:
      type: "object"
      example: {
        "message": "Password does not match"
      }


  500:
    description: "Error in query operation"
    schema:
      type: "object"
      example: {
        'error': 'Error while resetting the password'
      }

