summary: "Update the password"
tags:
  - platform/Users
description: "User can update their password"
produces:
- "application/json"
security:
  - Authorization: []

requestBody:
  required: true
  content:
    application/json:
      schema:
        required: [passowrd, new_password, confirm_password]
        properties:
          password:
            type: "string"
            required: true
          new_password:
            type: "string"
            required: true
          confirm_password:
            type: "string"
            required: true
        example: {"password":"test@123#" ,"new_password": "test@123#!", "confirm_password": "test@123#!"}


responses:
  200:
    description: "Success"
    schema:
      type: "object"
      example : {
        "message": "Password updated successfully"
      }

  400:
    description: "Insufficient details"
    schema:
      type: "object"
      example: {
        "message": "Insufficient details provided"
      }

  404:
    description: "User does not exist"
    schema:
      type: "object"
      example: {
        "message": "User does not exist"
      }


  500:
    description: "Error in query operation"
    schema:
      type: "object"
      example: {
        'error': 'Error while resetting the password'
      }

