#  base image
FROM mathcodex.azurecr.io/codex-python-alpine

LABEL maintainer shridhar@themathcompany.com
LABEL org mathco
LABEL platform codex
LABEL product client
LABEL image_type service_image

##adding version file
#ADD VERSION .

# # set working directory
# # RUN mkdir /usr/src/app
# # WORKDIR /usr/src/app

# # add `/usr/src/app/node_modules/.bin` to $PATH
# # ENV PATH /usr/src/app/node_modules/.bin:$PATH

# # install and cache app dependencies
# # COPY package.json /usr/src/app/package.json
# COPY ./ /app
# WORKDIR /app
# RUN npm install --silent
# # RUN npm install react-scripts@1.1.1 -g --silent
# # RUN npm run-script build
# # RUN npm install serve -g --silent

# # start app
# CMD ["npm", "start"]


# Copy the Nginx global conf
COPY nginx.conf /etc/nginx/

# Copy the React Nginx HTTP site conf
COPY react-http-site-nginx.conf /etc/nginx/conf.d/

# Copy the React Nginx HTTPS site conf
COPY react-https-site-nginx.conf /etc/nginx/conf.d/

# Custom Supervisord config
COPY supervisord.conf /etc/supervisord.conf

# Add app
COPY ./build /app
WORKDIR /app
RUN chown -R nginx:nginx /app

# Add certs
RUN mkdir /certs
COPY ./certs/client.crt /certs/client.crt
COPY ./certs/client.key /certs/client.key
RUN chown -R nginx:nginx /certs

# add entrypoint.sh
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["sh", "-c", "/entrypoint.sh"]

# test