summary: "Fetches the app screen widget details."
tags:
  - product/App
description: "Fetches the app screen widget details for given app and screen ID"
produces:
- "application/json"
security:
  - Authorization: []

parameters:
- in: "path"
  name: "app_id"
  required: "true"
  schema:
    type: "integer"
- in: "path"
  name: "screen_id"
  required: "true"
  schema:
    type: "integer"

requestBody:
  description: Details to update the widgets
  required: true
  content:
    application/json:
      schema:
        required: [widget, filters]
        properties:
          widget:
            type: "object"
          filters:
            type: "object"
        example: { "widget": { "id": 24, "widget_key": "Graph2"}, "filters": {"Region": "North America", "Country": "USA", "Category": "Category 1"}}

responses:
  200:
    description: "Success"
    content:
      application/json:
        schema:
          type: "object"
          example :
            data:
              widget_value_id: 1234
              value: []
              simulated_value: []

  500:
    description: "Error while fetching"
    content:
      application/json:
        schema:
          example: {
            'error': 'item not found'
          }
