summary: "Update widget."
tags:
  - product/App
description: "Update app screen widget details for given app and screen ID"
produces:
- "application/json"
security:
  - Authorization: []

parameters:
- in: "path"
  name: "app_id"
  required: "true"
  schema:
    type: "integer"
- in: "path"
  name: "screen_id"
  required: "true"
  schema:
    type: "integer"

requestBody:
  description: Details to update the widgets
  required: true
  content:
    application/json:
      schema:
        required: [widget, filters]
        properties:
          widget:
            type: "object"
            required: [widget_key]
            properties:
              "widget_key":
                type: "string"
          filters:
            type: "array"
            items:
              type: "object"
              required: [filter_key]
              properties:
                filter_key:
                  type: "object"
                  required: [checked]
                  properties:
                    type: "boolean"

responses:
  200:
    description: "Success"
    content:
      application/json:
        schema:
          type: "object"
          example :
            data:
              widget_value_id: 1234
              value: []
              simulated_value: []

  500:
    description: "Error while fetching"
    content:
      application/json:
        schema:
          example: {
            'error': 'item not found'
          }
