# Modify this line after testing on local system
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args: ['--maxkb=1200']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort-local
        entry : isort
        args: ["--profile", "black"]
        language: python
        types: [python]
        exclude: .+/(settings|migrations)/.+
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        args: ['--line-length','120']
        require_serial: true
        types_or: [python, pyi]
        exclude: |
          (?x)^(
              docker/services/server/api/migrations|
              docker/services/product-server/api/migrations|
              docker/services/product-client|
              docker/services/client
          )
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        name: flake8
        args: ['--max-line-length', '5000']
        description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
        entry: flake8
        language: python
        types: [python]
        exclude: |
          (?x)^(
              docker/services/server/api/migrations|
              docker/services/product-server/api/migrations|
              docker/services/product-client|
              docker/services/client
          )
# -   repo: local
#     hooks:
#     -   id: prettier
#         name: prettier
#         description: 'prettier-product-client'
#         entry: bash -c "cd docker/services/product-client && prettier --write --list-different --ignore-unknown 'src/**/*.{js,jsx}'"
#         exclude: |
#           (?x)^(
#               docker/services/product-client/src/__tests__|
#               docker/services/product-client/src/__mocks__
#           )
#         language: node
#         types_or: [css, javascript]
#         args: []
#         require_serial: false
#         additional_dependencies: ["prettier@3.0.0-alpha.6"]
#         minimum_pre_commit_version: '0'
#     -   id: eslint
#         name: eslint
#         description: 'eslint product-client'
#         entry: bash -c "cd docker/services/product-client && eslint . --ext=js,jsx --fix"
#         language: node
#         types: [javascript]
#         args: []
#         exclude: |
#           (?x)^(
#               docker/services/product-client/src/__tests__|
#               docker/services/product-client/src/__mocks__
#           )
#         require_serial: false
#         additional_dependencies: ["eslint@8.35.0"]
#         minimum_pre_commit_version: '0'