"""Add conversation request type and payload

Revision ID: 05013143e8f3
Revises: cb9f619d8b1b
Create Date: 2024-08-09 10:20:43.016797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "05013143e8f3"
down_revision: Union[str, None] = "cb9f619d8b1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("copilot_conversation", sa.Column("request_type", sa.String(length=100), nullable=True))
    op.add_column("copilot_conversation", sa.Column("request_payload", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("copilot_conversation", "request_payload")
    op.drop_column("copilot_conversation", "request_type")
    # ### end Alembic commands ###
