"""empty message

Revision ID: 06daed8828c1
Revises: a53baf3f40d8
Create Date: 2023-08-03 12:37:56.975020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06daed8828c1"
down_revision = "a53baf3f40d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problem_overview",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("contact", sa.String(length=100), nullable=True),
        sa.Column("metrics", sa.Text(), nullable=True),
        sa.Column("current_stage", sa.String(length=100), nullable=True),
        sa.Column("next_stage", sa.String(length=100), nullable=True),
        sa.Column("problem_definition_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["problem_definition_id"],
            ["problem_definition.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("problem_overview")
    # ### end Alembic commands ###
