"""empty message

Revision ID: 07f5fcad432d
Revises: e955454b6e7c
Create Date: 2024-07-30 12:49:31.933618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "07f5fcad432d"
down_revision: Union[str, None] = "e955454b6e7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "copilot_conversation_datasource_conversation_window_id_fkey",
        "copilot_conversation_datasource",
        type_="foreignkey",
    )
    op.drop_column("copilot_conversation_datasource", "conversation_window_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "copilot_conversation_datasource",
        sa.Column("conversation_window_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "copilot_conversation_datasource_conversation_window_id_fkey",
        "copilot_conversation_datasource",
        "copilot_conversation_window",
        ["conversation_window_id"],
        ["id"],
    )
    # ### end Alembic commands ###
