"""empty message

Revision ID: 100679ead5e7
Revises: e1bbf17f9da2
Create Date: 2023-05-10 15:56:10.098026

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "100679ead5e7"
down_revision = "c5690a73e721"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app",
        sa.Column("app_creator_id", sa.Integer(), nullable=False, server_default="0"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app", "app_creator_id")
    # ### end Alembic commands ###
