"""empty message

Revision ID: 1e58f36ff28b
Revises: d41d8cea9394
Create Date: 2021-11-26 15:38:57.537392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1e58f36ff28b"
down_revision = "d41d8cea9394"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "objectives_steps_widget_value",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("objectives_steps_id", sa.Integer(), nullable=True),
        sa.Column("widget_value", sa.JSON(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("sub_title", sa.Text(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["objectives_steps_id"],
            ["objectives_steps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("steps_content")
    op.add_column("objectives_steps", sa.Column("graph_type", sa.Text(), nullable=True))
    op.add_column("objectives_steps", sa.Column("horizontal", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objectives_steps", "horizontal")
    op.drop_column("objectives_steps", "graph_type")
    op.create_table(
        "steps_content",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("objectives_steps_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "content_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], name="steps_content_created_by_fkey"),
        sa.ForeignKeyConstraint(["deleted_by"], ["user.id"], name="steps_content_deleted_by_fkey"),
        sa.ForeignKeyConstraint(
            ["objectives_steps_id"],
            ["objectives_steps.id"],
            name="steps_content_objectives_steps_id_fkey",
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], name="steps_content_updated_by_fkey"),
        sa.PrimaryKeyConstraint("id", name="steps_content_pkey"),
    )
    op.drop_table("objectives_steps_widget_value")
    # ### end Alembic commands ###
