"""empty message

Revision ID: 1e735c98e379
Revises: b6a239d667b8
Create Date: 2021-06-25 00:40:46.301412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e735c98e379"
down_revision = "b6a239d667b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_screen", sa.Column("rating_url", sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_screen", "rating_url")
    # ### end Alembic commands ###
