"""empty message

Revision ID: 25837ba80106
Revises: 86d878b32c83
Create Date: 2024-03-14 10:40:27.089365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25837ba80106"
down_revision = "86d878b32c83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm_compute_config", sa.Column("estimated_cost", sa.Float(), nullable=True))
    op.add_column("llm_compute_config", sa.Column("data_disks", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm_compute_config", "data_disks")
    op.drop_column("llm_compute_config", "estimated_cost")
    # ### end Alembic commands ###
