"""empty message

Revision ID: 25a550d0084d
Revises: 8464d35132b3
Create Date: 2023-07-31 19:38:51.985854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25a550d0084d"
down_revision = "8464d35132b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "minerva_conversation_window",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column("pinned", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["minerva_apps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("minerva_conversation", sa.Column("conversation_window_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "minerva_conversation_window_application_id_fkey",
        "minerva_conversation",
        "minerva_conversation_window",
        ["conversation_window_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("minerva_conversation_window_application_id_fkey", "minerva_conversation", type_="foreignkey")
    op.drop_column("minerva_conversation", "conversation_window_id")
    op.drop_table("minerva_conversation_window")
    # ### end Alembic commands ###
