"""empty message

Revision ID: 27985ea4ff8f
Revises: a9af9899dd62
Create Date: 2024-06-27 12:57:43.870763

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "27985ea4ff8f"
down_revision = "a9af9899dd62"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conn_system_dashboard", sa.Column("small_logo_blob_name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conn_system_dashboard", "small_logo_blob_name")
    # ### end Alembic commands ###
