"""empty message

Revision ID: 2c713fa6f9e9
Revises: 3a3525603b0f
Create Date: 2021-04-01 00:59:29.653199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c713fa6f9e9"
down_revision = "3a3525603b0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story_layout",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("layout_style", sa.JSON(), nullable=True),
        sa.Column("layout_props", sa.JSON(), nullable=True),
        sa.Column("thumbnail_blob_name", sa.Text(), nullable=True),
        sa.Column("layout_name", sa.String(length=100), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Normally these indexex are already created.
    # op.create_index(op.f('ix_app_screen_widget_filter_value_app_id'), 'app_screen_widget_filter_value', ['app_id'], unique=False)
    # op.create_index(op.f('ix_app_screen_widget_filter_value_screen_id'), 'app_screen_widget_filter_value', ['screen_id'], unique=False)
    # op.create_index(op.f('ix_app_screen_widget_filter_value_widget_id'), 'app_screen_widget_filter_value', ['widget_id'], unique=False)
    # op.create_index(op.f('ix_app_screen_widget_filter_value_widget_value_id'), 'app_screen_widget_filter_value', ['widget_value_id'], unique=False)
    op.add_column("story", sa.Column("story_json", sa.Text(), nullable=True))
    op.add_column("story_content", sa.Column("content_json", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("story_content", "content_json")
    op.drop_column("story", "story_json")
    # op.drop_index(op.f('ix_app_screen_widget_filter_value_widget_value_id'), table_name='app_screen_widget_filter_value')
    # op.drop_index(op.f('ix_app_screen_widget_filter_value_widget_id'), table_name='app_screen_widget_filter_value')
    # op.drop_index(op.f('ix_app_screen_widget_filter_value_screen_id'), table_name='app_screen_widget_filter_value')
    # op.drop_index(op.f('ix_app_screen_widget_filter_value_app_id'), table_name='app_screen_widget_filter_value')
    op.drop_table("story_layout")
    # ### end Alembic commands ###
