"""Update progress_bar table

Revision ID: 3148ceadb19c
Revises: de761384327f
Create Date: 2024-08-27 15:26:27.792068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3148ceadb19c"
down_revision: Union[str, None] = "de761384327f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("progress_bar", sa.Column("stage_percentage", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("progress_bar", "stage_percentage")
    # ### end Alembic commands ###
