"""empty message

Revision ID: 3a3525603b0f
Revises: f85c100b2c43
Create Date: 2021-03-22 16:47:16.544868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3a3525603b0f"
down_revision = "f85c100b2c43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("app_id", sa.Integer(), nullable=True),
        sa.Column("system_created", sa.Boolean(), nullable=True),
        sa.Column("story_file_links", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["app.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "story_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("story_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=True),
        sa.Column("write", sa.Boolean(), nullable=True),
        sa.Column("delete", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["story.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "story_content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("story_id", sa.Integer(), nullable=True),
        sa.Column("app_id", sa.Integer(), nullable=True),
        sa.Column("app_screen_id", sa.Integer(), nullable=True),
        sa.Column("app_screen_widget_id", sa.Integer(), nullable=True),
        sa.Column("app_screen_widget_value_id", sa.Integer(), nullable=True),
        sa.Column("app_screen_widget_filter_value_id", sa.Integer(), nullable=True),
        sa.Column("orderby", sa.Integer(), nullable=True),
        sa.Column("layout_type", sa.String(length=100), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["app.id"],
        ),
        sa.ForeignKeyConstraint(
            ["app_screen_id"],
            ["app_screen.id"],
        ),
        sa.ForeignKeyConstraint(
            ["app_screen_widget_filter_value_id"],
            ["app_screen_widget_filter_value.id"],
        ),
        sa.ForeignKeyConstraint(
            ["app_screen_widget_id"],
            ["app_screen_widget.id"],
        ),
        sa.ForeignKeyConstraint(
            ["app_screen_widget_value_id"],
            ["app_screen_widget_value.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["story.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("report_content_filter_values")
    op.drop_table("report_access")
    op.drop_table("report_content")
    op.drop_table("report")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("app_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("system_created", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["app_id"], ["app.id"], name="report_app_id_fkey"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], name="report_created_by_fkey"),
        sa.ForeignKeyConstraint(["deleted_by"], ["user.id"], name="report_deleted_by_fkey"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], name="report_updated_by_fkey"),
        sa.PrimaryKeyConstraint("id", name="report_pkey"),
    )
    op.create_table(
        "report_access",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("report_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("read", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("write", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("delete", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], name="report_access_created_by_fkey"),
        sa.ForeignKeyConstraint(["deleted_by"], ["user.id"], name="report_access_deleted_by_fkey"),
        sa.ForeignKeyConstraint(["report_id"], ["report.id"], name="report_access_report_id_fkey"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], name="report_access_updated_by_fkey"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="report_access_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="report_access_pkey"),
    )
    op.create_table(
        "report_content",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("app_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("app_screen_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("app_screen_widget_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "app_screen_widget_value_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "app_screen_widget_filter_value_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("report_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["app_id"], ["app.id"], name="report_content_app_id_fkey"),
        sa.ForeignKeyConstraint(
            ["app_screen_id"],
            ["app_screen.id"],
            name="report_content_app_screen_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["app_screen_widget_filter_value_id"],
            ["app_screen_widget_filter_value.id"],
            name="report_content_app_screen_widget_filter_value_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["app_screen_widget_id"],
            ["app_screen_widget.id"],
            name="report_content_app_screen_widget_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["app_screen_widget_value_id"],
            ["app_screen_widget_value.id"],
            name="report_content_app_screen_widget_value_id_fkey",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], name="report_content_created_by_fkey"),
        sa.ForeignKeyConstraint(["deleted_by"], ["user.id"], name="report_content_deleted_by_fkey"),
        sa.ForeignKeyConstraint(["report_id"], ["report.id"], name="report_content_report_id_fkey"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], name="report_content_updated_by_fkey"),
        sa.PrimaryKeyConstraint("id", name="report_content_pkey"),
    )

    op.create_table(
        "report_content_filter_values",
        sa.Column("report_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("filter_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["filter_id"],
            ["app_screen_widget_filter_value.id"],
            name="report_content_filter_values_filter_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.id"],
            name="report_content_filter_values_report_id_fkey",
        ),
    )

    op.drop_table("story_content")
    op.drop_table("story_access")
    op.drop_table("story")
    # ### end Alembic commands ###
