"""wudget_filter_value column added in appscreenwidgetvalue table

Revision ID: 3beeec077dc4
Revises: 069a6434b22c
Create Date: 2024-09-26 12:28:03.395953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3beeec077dc4"
down_revision: Union[str, None] = "069a6434b22c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_screen_widget_value", sa.Column("widget_filter_value", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_screen_widget_value", "widget_filter_value")
    # ### end Alembic commands ###
