"""empty message

Revision ID: 4736d7e22a9a
Revises: decf6c3eceb1
Create Date: 2022-10-25 14:02:28.621502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4736d7e22a9a"
down_revision = "decf6c3eceb1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dynamic_viz_execution_environment_defaults",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("py_version", sa.String(length=100), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("ALTER TABLE public.dynamic_viz_execution_environment ALTER COLUMN requirements TYPE TEXT;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dynamic_viz_execution_environment_defaults")
    op.execute("ALTER TABLE public.dynamic_viz_execution_environment ALTER COLUMN requirements TYPE JSON;")
    # ### end Alembic commands ###
