"""empty message

Revision ID: 47fa5a613593
Revises: 100679ead5e7
Create Date: 2023-05-19 16:10:52.474137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47fa5a613593"
down_revision = "100679ead5e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_screen_ai_response_rating",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("app_id", sa.Integer(), nullable=True),
        sa.Column("screen_id", sa.Integer(), nullable=True),
        sa.Column("response_rating", sa.Integer(), nullable=True),
        sa.Column("response_rating_by_email", sa.String(length=1000), nullable=True),
        sa.Column("response_rating_by_name", sa.String(length=1000), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["app.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["screen_id"],
            ["app_screen.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_app_screen_ai_response_rating_app_id"),
        "app_screen_ai_response_rating",
        ["app_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_app_screen_ai_response_rating_screen_id"),
        "app_screen_ai_response_rating",
        ["screen_id"],
        unique=False,
    )
    op.add_column("app_screen", sa.Column("ai_response", sa.Text(), nullable=True))
    op.add_column(
        "app_screen",
        sa.Column("ai_response_verified_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "app_screen",
        sa.Column("ai_response_verified_email", sa.String(length=1000), nullable=True),
    )
    op.add_column(
        "app_screen",
        sa.Column("ai_response_verified_name", sa.String(length=1000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_screen", "ai_response_verified_name")
    op.drop_column("app_screen", "ai_response_verified_email")
    op.drop_column("app_screen", "ai_response_verified_at")
    op.drop_column("app_screen", "ai_response")
    op.drop_index(
        op.f("ix_app_screen_ai_response_rating_screen_id"),
        table_name="app_screen_ai_response_rating",
    )
    op.drop_index(
        op.f("ix_app_screen_ai_response_rating_app_id"),
        table_name="app_screen_ai_response_rating",
    )
    op.drop_table("app_screen_ai_response_rating")
    # ### end Alembic commands ###
