"""empty message

Revision ID: 49c156f6b116
Revises: e4f6bc1ee32f
Create Date: 2021-04-09 01:54:51.559773

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "49c156f6b116"
down_revision = "e4f6bc1ee32f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None,
        "story_content",
        [
            "app_id",
            "app_screen_id",
            "app_screen_widget_id",
            "app_screen_widget_value_id",
            "story_id",
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "story_content", type_="unique")
    # ### end Alembic commands ###
