"""version was added to scenario table

Revision ID: 4bf53ec5a8f3
Revises: a0d8f9162960
Create Date: 2024-11-20 13:20:02.937548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bf53ec5a8f3'
down_revision: Union[str, None] = '59454d7463f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('version', sa.String(), server_default='V.1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'version')
   