"""empty message

Revision ID: 518467c76d9a
Revises: 5cbb992c3fc4
Create Date: 2024-03-11 18:21:26.526719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "518467c76d9a"
down_revision = "5cbb992c3fc4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_model_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llm_model_type_mapping",
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["llm_model_registry.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["llm_model_type.id"],
        ),
        sa.PrimaryKeyConstraint("model_id", "type_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_model_type_mapping")
    op.drop_table("llm_model_type")
    # ### end Alembic commands ###
