"""empty message

Revision ID: 59308ead5e99
Revises: d94209e56cca
Create Date: 2024-08-01 08:59:35.300675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "59308ead5e99"
down_revision: Union[str, None] = "d94209e56cca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("copilot_conversation", sa.Column("extra_info", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("copilot_conversation", "extra_info")
    # ### end Alembic commands ###
