"""empty message

Revision ID: 5cbb992c3fc4
Revises: ed0194f5faa4
Create Date: 2024-03-04 18:21:35.128956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5cbb992c3fc4"
down_revision = "ed0194f5faa4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm_experiment", sa.Column("error_metric_type", sa.String(length=255), nullable=True))
    op.add_column("llm_experiment_checkpoint", sa.Column("train_result_path", sa.String(length=255), nullable=True))
    op.add_column("llm_experiment_checkpoint", sa.Column("eval_path", sa.String(length=255), nullable=True))
    op.add_column("llm_experiment_checkpoint", sa.Column("eval_status", sa.String(length=255), nullable=True))
    op.add_column("llm_experiment_checkpoint", sa.Column("eval_result", sa.Text(), nullable=True))
    op.drop_column("llm_experiment_checkpoint", "checkpoint_eval_path")
    op.drop_column("llm_experiment_checkpoint", "checkpoint_train_result_path")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "llm_experiment_checkpoint",
        sa.Column("checkpoint_train_result_path", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "llm_experiment_checkpoint",
        sa.Column("checkpoint_eval_path", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.drop_column("llm_experiment_checkpoint", "eval_result")
    op.drop_column("llm_experiment_checkpoint", "eval_status")
    op.drop_column("llm_experiment_checkpoint", "eval_path")
    op.drop_column("llm_experiment_checkpoint", "train_result_path")
    op.drop_column("llm_experiment", "error_metric_type")
    # ### end Alembic commands ###
