"""add conversation error flag

Revision ID: 5f49219d2ec6
Revises: 827e17882a94
Create Date: 2024-10-09 11:26:07.954319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5f49219d2ec6"
down_revision: Union[str, None] = "827e17882a94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("copilot_conversation", sa.Column("error", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("copilot_conversation", "error")
    # ### end Alembic commands ###
