"""empty message

Revision ID: 61a82d7e561b
Revises: 5d4e1868b914
Create Date: 2020-08-26 21:39:01.117531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61a82d7e561b"
down_revision = "5d4e1868b914"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "app_screen_widget_filter_value_widget_value_id_fkey",
        "app_screen_widget_filter_value",
        type_="foreignkey",
    )
    op.drop_column("app_screen_widget_filter_value", "widget_value_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_screen_widget_filter_value",
        sa.Column("widget_value_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "app_screen_widget_filter_value_widget_value_id_fkey",
        "app_screen_widget_filter_value",
        "app_screen_widget_value",
        ["widget_value_id"],
        ["id"],
    )
    # ### end Alembic commands ###
