"""empty message

Revision ID: 61a82d7e561b
Revises: 5d4e1868b914
Create Date: 2020-08-26 21:39:01.117531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


def drop_constraints(op, table_name, column_name):
    conn = op.get_bind()
    inspector = inspect(conn)

    # Define your table and column names
    table_name = table_name
    column_name = column_name
    # Get the dynamically generated foreign key constraint name
    foreign_keys = inspector.get_foreign_keys(table_name)
    print(foreign_keys)

    # Find the correct foreign key constraint dynamically
    constraint_name = None
    for fk in foreign_keys:
        if fk["constrained_columns"] == [column_name]:
            constraint_name = fk["name"]
            break

    if constraint_name:
        # Drop the foreign key constraint using its dynamic name
        op.drop_constraint(constraint_name, table_name, type_="foreignkey")

# revision identifiers, used by Alembic.
revision = "61a82d7e561b"
down_revision = "5d4e1868b914"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(
    #     "app_screen_widget_filter_value_widget_value_id_fkey",
    #     "app_screen_widget_filter_value",
    #     type_="foreignkey",
    # )
    drop_constraints(op, "app_screen_widget_filter_value", "widget_value_id")

    op.drop_column("app_screen_widget_filter_value", "widget_value_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_screen_widget_filter_value",
        sa.Column("widget_value_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "app_screen_widget_filter_value_widget_value_id_fkey",
        "app_screen_widget_filter_value",
        "app_screen_widget_value",
        ["widget_value_id"],
        ["id"],
    )
    # ### end Alembic commands ###
