"""Update progress_bar table

Revision ID: 62c560f55bb2
Revises: 3148ceadb19c
Create Date: 2024-08-27 18:28:20.001694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62c560f55bb2"
down_revision: Union[str, None] = "3148ceadb19c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("progress_bar", sa.Column("type", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("progress_bar", "type")
    # ### end Alembic commands ###
