"""empty message

Revision ID: 72763877f991
Revises: bd96d90031c7
Create Date: 2021-11-30 23:51:08.716729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "72763877f991"
down_revision = "bd96d90031c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "objectives",
        sa.Column("next_recommended_objective", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objectives", "next_recommended_objective")
    # ### end Alembic commands ###
