"""empty message

Revision ID: 733139013140
Revises: ce954b0386ce
Create Date: 2022-02-07 19:00:49.364827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "733139013140"
down_revision = "ce954b0386ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("user_email", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alerts", "user_email")
    # ### end Alembic commands ###
