"""empty message

Revision ID: 773015ee88f9
Revises: 84a274163ec0
Create Date: 2021-11-09 07:13:23.333544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "773015ee88f9"
down_revision = "1453dd17178d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_screen", sa.Column("screen_auto_refresh", sa.Boolean(), nullable=True))
    # op.drop_column('story_content', 'content_json')
    # op.drop_column('story_content', 'filter_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('story_content', sa.Column('filter_data', sa.TEXT(), autoincrement=False, nullable=True))
    # op.add_column('story_content', sa.Column('content_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column("app_screen", "screen_auto_refresh")
    # ### end Alembic commands ###
