"""empty message

Revision ID: 784d45ff14a6
Revises: 7d8ab4ba02b7
Create Date: 2021-01-14 13:11:29.191740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "784d45ff14a6"
down_revision = "7d8ab4ba02b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app", sa.Column("logo_blob_name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app", "logo_blob_name")
    # ### end Alembic commands ###
