"""empty message

Revision ID: 7cf756e8ec14
Revises: 4736d7e22a9a
Create Date: 2022-10-13 16:54:39.201366

"""

# NOTE: THIS IS WHERE I MERGE HIERARCHY CHANGES. THIS NEEDS TO BE HANDLED CORRECTLY
# WHEN BEING MERGED INTO DEVELOP
# ORIGINAL HEADS: 5d545cfc114a -->1f1ece569d7e
# AND 5d545cfc114a --> 4736d7e22a9a
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7cf756e8ec14"
down_revision = "5d545cfc114a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("functions", sa.Column("parent_function_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "functions_parent_function_id_fkey",
        "functions",
        "functions",
        ["parent_function_id"],
        ["id"],
    )
    op.add_column("industry", sa.Column("parent_industry_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "industry_parent_industry_id_fkey",
        "industry",
        "industry",
        ["parent_industry_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("industry_parent_industry_id_fkey", "industry", type_="foreignkey")
    op.drop_column("industry", "parent_industry_id")
    op.drop_constraint("functions_parent_function_id_fkey", "functions", type_="foreignkey")
    op.drop_column("functions", "parent_function_id")
    # ### end Alembic commands ###
