"""empty message

Revision ID: 8bd41338a341
Revises: 18e88a9fb5fc
Create Date: 2020-08-26 21:15:35.256506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8bd41338a341"
down_revision = "18e88a9fb5fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_screen", sa.Column("app_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "app_screen", "app", ["app_id"], ["id"])
    op.add_column("app_screen_widget", sa.Column("app_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "app_screen_widget", "app", ["app_id"], ["id"])
    op.add_column(
        "app_screen_widget_filter_value",
        sa.Column("app_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(None, "app_screen_widget_filter_value", "app", ["app_id"], ["id"])
    op.add_column("app_screen_widget_value", sa.Column("app_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "app_screen_widget_value", "app", ["app_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "app_screen_widget_value", type_="foreignkey")
    op.drop_column("app_screen_widget_value", "app_id")
    op.drop_constraint(None, "app_screen_widget_filter_value", type_="foreignkey")
    op.drop_column("app_screen_widget_filter_value", "app_id")
    op.drop_constraint(None, "app_screen_widget", type_="foreignkey")
    op.drop_column("app_screen_widget", "app_id")
    op.drop_constraint(None, "app_screen", type_="foreignkey")
    op.drop_column("app_screen", "app_id")
    # ### end Alembic commands ###
