"""empty message

Revision ID: 8f200fa424f6
Revises: d93457e597b1
Create Date: 2021-12-20 12:22:47.415718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f200fa424f6"
down_revision = "d93457e597b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("app_id", sa.Integer(), nullable=True),
        sa.Column("permissions", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["app.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_app_user_role_app_id"), "app_user_role", ["app_id"], unique=False)
    op.create_table(
        "app_user_role_identifier",
        sa.Column("app_user_role_id", sa.Integer(), nullable=True),
        sa.Column("app_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["app_user_role_id"],
            ["app_user_role.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_user_role_identifier")
    op.drop_index(op.f("ix_app_user_role_app_id"), table_name="app_user_role")
    op.drop_table("app_user_role")
    # ### end Alembic commands ###
