"""empty message

Revision ID: 9647592a2d9c
Revises: e24c60c21b97
Create Date: 2020-09-28 00:47:12.243456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9647592a2d9c"
down_revision = "e24c60c21b97"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app", sa.Column("blueprint_link", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app", "blueprint_link")
    # ### end Alembic commands ###
