"""Update orchestrator_config

Revision ID: 966a6acd65e5
Revises: fdf7bbd84c96
Create Date: 2024-09-04 13:28:21.771984

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "966a6acd65e5"
down_revision: Union[str, None] = "fdf7bbd84c96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """update public.copilot_app set orchestrator_config = jsonb_set(orchestrator_config::jsonb, '{convo_memory_enabled}', 'true', true)::json where orchestrator_config::TEXT <> 'null' and deleted_at is null ;"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
