"""empty message

Revision ID: 969ce2a3fc64
Revises: 0714b50e7b47
Create Date: 2021-05-23 13:59:23.160264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "969ce2a3fc64"
down_revision = "0714b50e7b47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("story_share", sa.Column("shared_by", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("story_share", "shared_by")
    # ### end Alembic commands ###
