"""empty message

Revision ID: 9d0b5ae5592e
Revises: a1867d30ad31
Create Date: 2023-04-05 18:04:22.588420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d0b5ae5592e"
down_revision = "a1867d30ad31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_screen", sa.Column("user_guide", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_screen", "user_guide")
    # ### end Alembic commands ###
