"""empty message

Revision ID: a65f1d9cdb4e
Revises: e06af44e166c
Create Date: 2023-05-05 17:22:26.094304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a65f1d9cdb4e"
down_revision = "e06af44e166c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("dashboard", sa.Column("dashboard_url", sa.String(length=2000), nullable=True))
    op.add_column("dashboard", sa.Column("dashboard_template_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "dashboard_dashboard_template_id_fkey",
        "dashboard",
        "dashboard_templates",
        ["dashboard_template_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("dashboard_dashboard_template_id_fkey", "dashboard", type_="foreignkey")
    op.drop_column("dashboard", "dashboard_template_id")
    op.drop_column("dashboard", "dashboard_url")
    op.drop_table("dashboard_templates")
    # ### end Alembic commands ###
