"""empty message

Revision ID: c3b74cbe61e4
Revises: 6cc88c8f6ba6
Create Date: 2023-07-13 17:06:23.732001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3b74cbe61e4"
down_revision = "6cc88c8f6ba6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_screen", sa.Column("marked", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_screen", "marked")
    # ### end Alembic commands ###
