"""empty message

Revision ID: c716815e5439
Revises: 947f792e81b7
Create Date: 2024-05-29 19:12:02.101742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c716815e5439"
down_revision = "947f792e81b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dsw_execution_environment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("desc", sa.Text(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dsw_execution_environment_project_mapping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("execution_environment_id", sa.Integer(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["execution_environment_id"],
            ["dsw_execution_environment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("execution_environment_project_mapping")
    op.drop_table("execution_environment")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_environment_project_mapping",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("execution_environment_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("config", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], name="execution_environment_project_mapping_created_by_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"], ["user.id"], name="execution_environment_project_mapping_deleted_by_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["execution_environment_id"],
            ["execution_environment.id"],
            name="execution_environment_project_map_execution_environment_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name="execution_environment_project_mapping_project_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["user.id"], name="execution_environment_project_mapping_updated_by_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="execution_environment_project_mapping_pkey"),
    )
    op.create_table(
        "execution_environment",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("desc", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("config", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], name="execution_environment_created_by_fkey"),
        sa.ForeignKeyConstraint(["deleted_by"], ["user.id"], name="execution_environment_deleted_by_fkey"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], name="execution_environment_updated_by_fkey"),
        sa.PrimaryKeyConstraint("id", name="execution_environment_pkey"),
    )
    op.drop_table("dsw_execution_environment_project_mapping")
    op.drop_table("dsw_execution_environment")
    # ### end Alembic commands ###
