"""scenario_List was added to comment table

Revision ID: ccd7ebd9f437
Revises: f3c15b3cf0ac
Create Date: 2024-11-21 11:45:00.381361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccd7ebd9f437'
down_revision: Union[str, None] = 'f3c15b3cf0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('scenario_list', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'scenario_list')
    # ### end Alembic commands ###
