"""Add skillset deployment_agent

Revision ID: d3182a511ca3
Revises: 5f49219d2ec6
Create Date: 2024-10-15 15:56:22.491257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d3182a511ca3"
down_revision: Union[str, None] = "5f49219d2ec6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "copilot_tool_version_registry_mapping", sa.Column("deployment_agent", sa.String(length=100), nullable=True)
    )
    op.execute("UPDATE copilot_tool_version_registry_mapping SET deployment_agent = 'FISSION'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("copilot_tool_version_registry_mapping", "deployment_agent")

    # ### end Alembic commands ###
