"""empty message

Revision ID: d37e3ad0880a
Revises: dd3aef88aba1
Create Date: 2022-12-14 11:53:16.255607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d37e3ad0880a"
down_revision = "1f1ece569d7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("app_mapping", "industry_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("app_mapping", "function_id", existing_type=sa.INTEGER(), nullable=True)
    op.add_column("industry", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("industry", "description")
    op.alter_column("app_mapping", "function_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("app_mapping", "industry_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
