"""copilot test skillset

Revision ID: fdf7bbd84c96
Revises: 493670e84777
Create Date: 2024-07-17 23:12:26.599029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdf7bbd84c96"
down_revision: Union[str, None] = "6f33a9100db2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("copilot_app", sa.Column("is_test", sa.Boolean(), nullable=True))
    op.add_column("copilot_tool_registry", sa.Column("is_test", sa.Boolean(), nullable=True))
    op.add_column("copilot_tool_version", sa.Column("is_test", sa.Boolean(), nullable=True))
    op.execute(
        """INSERT INTO copilot_tool_registry
(name, "desc", is_test)
VALUES('Local', 'Registry to publish local skillsets for test and debug', 1);
"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("copilot_tool_version", "is_test")
    op.drop_column("copilot_tool_registry", "is_test")
    op.drop_column("copilot_app", "is_test")
    # ### end Alembic commands ###
