summary: "Update app details"
tags:
  - product/AppAdmin
description: "Updates the app details for the given appID"
produces:
- "application/json"
security:
  - Authorization: []

parameters:
- in: "path"
  name: "app_id"
  required: "true"
  schema:
    type: "integer"

requestBody:
  description: Details to update the app
  required: true
  content:
    application/json:
      schema:
        required: [app_name]
        properties:
          theme_id:
            type: number
        example: {"theme_id": 1}

responses:
  200:
    description: "Updated successfully"
    schema:
      type: "object"
      example: {'status': 'success'}
  500:
    description: "Error while updating"
    schema :
      type: "object"
      example:  {'error': 'Error in applying theme'}