summary: "Get app variable value"
tags:
  - product/AppAdmin
description: "Returns value for existing app variable"
produces:
- "application/json"
security:
  - Authorization: []

parameters:
- in: "path"
  name: "app_id"
  required: "true"
  schema:
    type: "integer"

- in: "path"
  name: "key"
  required: "true"
  schema:
    type: "string"

responses:
  200:
    description: "Returns app variable value corresponding to the given key"
    schema:
      type: "object"
  404:
    description: "Error in deleting, key doesnt exist"
    schema :
      type: "object"
      example:  {'error': 'Error in fetch operation, variable does not exist in application variables'}
  500:
    description: "Error while deleting"
    schema :
      type: "object"
      example:  {'error': 'Error fetching application variable information'}