summary: "Update app details"
tags:
  - product/AppAdmin
description: "Updates the app details for the given appID"
produces:
- "application/json"
security:
  - Authorization: []

parameters:
- in: "path"
  name: "app_id"
  required: "true"
  schema:
    type: "integer"

requestBody:
  description: Details to update the app
  required: true
  content:
    application/json:
      schema:
        required: [app_name, industry, industry_id, contact_email]
        properties:
          app_name:
            type: "string"
          industry:
            type: "string"
          industry_id:
            type: "interger"
          function:
            type: "string"
          function_id:
            type: "integer"
          contact_email:
            type: "string"
          description:
            type: "string"
          logo_blob_name:
            type: "string"
          problem_area:
            type: "string"
          small_logo_blob_name:
            type: "string"
        example: {"app_name": "App Local-1", "industry": "Test", "function" :"test function", "contact_email": "abc@themathcompany.com", "logo_blob_name": "", "small_logo_blob_name": "", "description": "", "problem_area": "", "industry_id": 1, "function_id": 1}

responses:
  200:
    description: "Updated successfully"
    schema:
      type: "object"
      example: {'status': 'success'}
  500:
    description: "Error while updating"
    schema :
      type: "object"
      example:  {'error': 'Error in updating application overview'}