summary: "Bulk upload users"
tags:
  - platform/Bulk Users
description: "This accepts a xls file and inserts all unique rows or re-instates access to previously deleted users."
consumes:
- multipart/form-data
produces:
- "application/json"
security:
  - Authorization: []
requestBody:
  content:
    multipart/form-data:
      schema:
        type: object
        properties:
          # 'file' will be the field name in this multipart request
          file:
            type: string
            format: binary

responses:
  200:
    description: "Success"
    content:
      application/json:
        schema:
          type: object
          properties:
            filename:
              type: string
            users_added:
              type: int
            users_ignored:
              type: int
            user_access_reinstated:
              type: int
          example:
              filename: filename.xls
              users_added: 10
              users_ignored: 10
              user_access_reinstated: 10


  400:
    description: "File format is not accepted.Please upload .XLS file / Please remove empty values from file / Please remove duplicates in email / Restricted User column can only accept Yes/No /Enter Valid email"

