summary: "List of widget groups"
tags:
  - platform/WidgetGroups
description: "This returns the list of widget group along with their details."
produces:
- "application/json"
security:
  - Authorization: []
responses:
  200:
    description: "Success"
    schema:
      type: "object"
      example: [
          {
              "id": 123,
              "name": "WidgetName",
              "created_by":  '--',
              "updated_by":  '--',
              "created_at": "--",
              "updated_at":  "--",
              "widget_count": 2
          }
        ]
  500:
    description: "Yet to be added in api"
    schema:
    type: "object"
    example: [
      "Error":"Error in query operation"
    ]
