summary: "Create Execution environment"
tags:
  - product/ExecutionEnvironment
description: "Create Execution environment to execute project solution"
consumes:
- application/json
produces:
- application/json
security:
  - Authorization: []

requestBody:
  required: true
  content:
    application/json:
      schema:
        required: [name]
        properties:
          name:
            type: string
          desc:
            type: string
          config:
            type: object
        example: {'name': "Execution Env1", 'desc': "desc", 'config': {''}}

responses:
  200:
    description: "API successful"
    schema:
      type: object
  500:
    description: "Error"
    schema:
      type: object
    example: {'status': 'error', 'error': 'Error creating execution environment'}

