FROM mathcodex.azurecr.io/codex-base-exec-env:latest

LABEL maintainer anoop.s@themathcompany.com
LABEL org mathco
LABEL platform codex
LABEL image_type dynamic_viz_exec_env

# Transfer flask app
WORKDIR /app
COPY . /app
RUN chmod -R 777 run_webserver_prestage.sh

# Run flask server
CMD ["sh", "-c", "/app/run_webserver_prestage.sh"]