"""empty message

Revision ID: 02606e5c959e
Revises: 9df4fe52df9a
Create Date: 2022-03-30 17:29:31.425413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02606e5c959e"
down_revision = "9df4fe52df9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_notebook_config", sa.Column("config_code", sa.Text(), nullable=True)
    )
    op.add_column(
        "project_notebook_config", sa.Column("config_df", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_notebook_config", "config_df")
    op.drop_column("project_notebook_config", "config_code")
    # ### end Alembic commands ###
