"""empty message

Revision ID: 0a91196c5dfa
Revises: 5f37dbe98b01
Create Date: 2021-02-24 09:20:59.301592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a91196c5dfa"
down_revision = "e1deb291f5a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_config", sa.Column("deploy_logs", sa.Text(), nullable=True))
    op.add_column("app_config", sa.Column("deploy_status", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_config", "deploy_status")
    op.drop_column("app_config", "deploy_logs")
    # ### end Alembic commands ###
