"""empty message

Revision ID: 0ee78986076a
Revises: 6b4e5d54ed10
Create Date: 2020-01-05 14:20:52.247986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ee78986076a"
down_revision = "6b4e5d54ed10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
