"""empty message

Revision ID: 1298e9903a0c
Revises: 1b019ceaf563
Create Date: 2019-05-17 18:10:24.384826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1298e9903a0c"
down_revision = "1b019ceaf563"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feature", sa.Column("data_set_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "feature", "data_set", ["data_set_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feature", type_="foreignkey")
    op.drop_column("feature", "data_set_id")
    # ### end Alembic commands ###
