"""empty message

Revision ID: 153ddab42d1c
Revises: 6685496a3a68
Create Date: 2020-04-20 09:47:26.038046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "153ddab42d1c"
down_revision = "6685496a3a68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_group", sa.Column("all_projects", sa.Boolean(), nullable=True))
    op.add_column("user_group", sa.Column("app", sa.Boolean(), nullable=True))
    op.add_column("user_group", sa.Column("my_projects", sa.Boolean(), nullable=True))
    op.drop_column("user_group", "model_train")
    op.drop_column("user_group", "model_pipelines")
    op.drop_column("user_group", "data_prep")
    op.drop_column("user_group", "app_builder")

    op.execute("UPDATE user_group SET app = true WHERE id = 1")
    op.execute(
        "UPDATE user_group SET app = true, my_projects = true, all_projects = true WHERE id = 2"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_group",
        sa.Column("app_builder", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user_group",
        sa.Column("data_prep", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user_group",
        sa.Column("model_pipelines", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user_group",
        sa.Column("model_train", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("user_group", "my_projects")
    op.drop_column("user_group", "app")
    op.drop_column("user_group", "all_projects")
    # ### end Alembic commands ###
