"""empty message

Revision ID: 177598c0bd81
Revises: 854f2d945c07
Create Date: 2022-03-09 19:51:42.932462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "177598c0bd81"
down_revision = "854f2d945c07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_notebook", sa.Column("exec_logs", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_notebook", "exec_logs")
    # ### end Alembic commands ###
