"""empty message

Revision ID: 1b019ceaf563
Revises: 2fc217bb0b4d
Create Date: 2019-05-17 17:34:33.826505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b019ceaf563"
down_revision = "2fc217bb0b4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feature", sa.Column("business_impute", sa.Integer(), nullable=True))
    op.add_column(
        "feature", sa.Column("comments", sa.String(length=10000), nullable=True)
    )
    op.add_column(
        "feature", sa.Column("data_mean", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "feature", sa.Column("data_median", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "feature", sa.Column("data_mode", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "feature", sa.Column("data_type", sa.String(length=100), nullable=True)
    )
    op.add_column("feature", sa.Column("ignore", sa.Boolean(), nullable=True))
    op.add_column("feature", sa.Column("impute_task_id", sa.Integer(), nullable=True))
    op.add_column("feature", sa.Column("missing_percentage", sa.Float(), nullable=True))
    op.add_column("feature", sa.Column("no_factors", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "feature", "task", ["impute_task_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feature", type_="foreignkey")
    op.drop_column("feature", "no_factors")
    op.drop_column("feature", "missing_percentage")
    op.drop_column("feature", "impute_task_id")
    op.drop_column("feature", "ignore")
    op.drop_column("feature", "data_type")
    op.drop_column("feature", "data_mode")
    op.drop_column("feature", "data_median")
    op.drop_column("feature", "data_mean")
    op.drop_column("feature", "comments")
    op.drop_column("feature", "business_impute")
    # ### end Alembic commands ###
