"""empty message

Revision ID: 1be03f69a363
Revises: 28259bd878cf
Create Date: 2019-05-19 01:36:14.335547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1be03f69a363"
down_revision = "28259bd878cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("find_categorical_columns", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "task", sa.Column("find_continous_columns", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "task", sa.Column("find_primarykey_columns", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "task", sa.Column("remove_constant_columns", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "task", sa.Column("remove_datetime_columns", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "task", sa.Column("remove_duplicate_columns", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "remove_duplicate_columns")
    op.drop_column("task", "remove_datetime_columns")
    op.drop_column("task", "remove_constant_columns")
    op.drop_column("task", "find_primarykey_columns")
    op.drop_column("task", "find_continous_columns")
    op.drop_column("task", "find_categorical_columns")
    # ### end Alembic commands ###
