"""empty message

Revision ID: 20b05a68be5e
Revises: 7c9269b1769a
Create Date: 2020-04-20 08:27:42.823167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20b05a68be5e"
down_revision = "7c9269b1769a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("reviewer", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "project", "user", ["reviewer"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project", type_="foreignkey")
    op.drop_column("project", "reviewer")
    # ### end Alembic commands ###
