"""empty message

Revision ID: 20ba8403b9cf
Revises: 46beb363ffda
Create Date: 2022-07-22 11:47:29.895508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20ba8403b9cf"
down_revision = "46beb363ffda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "execution_environment",
        sa.Column("py_version", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("execution_environment", "py_version")
    # ### end Alembic commands ###
