"""empty message

Revision ID: 30fbaaaf5426
Revises: d26fbf896eba
Create Date: 2020-03-29 19:25:35.674503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30fbaaaf5426"
down_revision = "d26fbf896eba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("blueprint", sa.String(length=100000), nullable=True)
    )
    op.add_column(
        "project", sa.Column("design_metadata", sa.String(length=100000), nullable=True)
    )
    op.drop_column("project", "design")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "design", sa.VARCHAR(length=100000), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("project", "design_metadata")
    op.drop_column("project", "blueprint")
    # ### end Alembic commands ###
