"""empty message

Revision ID: 3c6c2ed48c04
Revises: a7b919dd953a
Create Date: 2019-05-10 14:54:34.457160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3c6c2ed48c04"
down_revision = "a7b919dd953a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_group", "model_predict")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_group",
        sa.Column("model_predict", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
