"""empty message

Revision ID: 46beb363ffda
Revises: 02606e5c959e
Create Date: 2022-05-10 14:33:10.698650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "46beb363ffda"
down_revision = "02606e5c959e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "execution_environment", sa.Column("config", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("execution_environment", "config")
    # ### end Alembic commands ###
