"""empty message

Revision ID: 47ebfbf725da
Revises: bb74a5b241b0
Create Date: 2020-05-03 20:59:15.057889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47ebfbf725da"
down_revision = "bb74a5b241b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_group", sa.Column("case_studies", sa.Boolean(), nullable=True))

    op.execute("UPDATE user_group SET case_studies = true WHERE id = 2")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_group", "case_studies")
    # ### end Alembic commands ###
