"""empty message

Revision ID: 48000e349e5f
Revises: cb1ebac1e2b9
Create Date: 2021-06-03 17:58:33.000683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48000e349e5f"
down_revision = "cb1ebac1e2b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("restricted_user", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "restricted_user")
    # ### end Alembic commands ###
