"""empty message

Revision ID: 50790be30c81
Revises: edd9720f6758
Create Date: 2020-05-19 09:07:56.050726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "50790be30c81"
down_revision = "edd9720f6758"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("widget_group", sa.Column("in_port", sa.Boolean(), nullable=True))
    op.add_column("widget_group", sa.Column("out_port", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("widget_group", "out_port")
    op.drop_column("widget_group", "in_port")
    # ### end Alembic commands ###
