"""empty message

Revision ID: 5551cfe85761
Revises: 53bfc7d67e72
Create Date: 2019-08-08 09:21:36.094370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5551cfe85761"
down_revision = "53bfc7d67e72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "experiment_execution",
        sa.Column("execution_data", sa.String(length=1000000), nullable=True),
    )
    op.add_column(
        "experiment_execution",
        sa.Column("logs", sa.String(length=100000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("experiment_execution", "logs")
    op.drop_column("experiment_execution", "execution_data")
    # ### end Alembic commands ###
