"""empty message

Revision ID: 631432052a57
Revises: 20ba8403b9cf
Create Date: 2022-11-21 16:43:35.143387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "631432052a57"
down_revision = "20ba8403b9cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_group", sa.Column("prod_app_publish", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_group", "prod_app_publish")
    # ### end Alembic commands ###
