"""empty message

Revision ID: 6685496a3a68
Revises: 20b05a68be5e
Create Date: 2020-04-20 08:37:18.444529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6685496a3a68"
down_revision = "20b05a68be5e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("project_status", sa.Integer(), nullable=True))
    op.drop_column("project", "status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("status", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_column("project", "project_status")
    # ### end Alembic commands ###
