"""empty message

Revision ID: 7029050f706a
Revises: 5551cfe85761
Create Date: 2019-11-17 01:30:59.780858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7029050f706a"
down_revision = "5551cfe85761"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_source",
        sa.Column("datasource_subtype", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_source", "datasource_subtype")
    # ### end Alembic commands ###
