"""empty message

Revision ID: 713cacc8a910
Revises: 232ba8a4dc78
Create Date: 2019-05-24 20:53:34.270190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "713cacc8a910"
down_revision = "232ba8a4dc78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("task_params", sa.String(length=10000), nullable=True)
    )
    op.drop_column("task", "remove_duplicate_columns")
    op.drop_column("task", "create_dummy_columns")
    op.drop_column("task", "find_continous_columns")
    op.drop_column("task", "remove_constant_columns")
    op.drop_column("task", "remove_datetime_columns")
    op.drop_column("task", "find_categorical_columns")
    op.drop_column("task", "find_primarykey_columns")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "find_primarykey_columns", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "task",
        sa.Column(
            "find_categorical_columns", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "task",
        sa.Column(
            "remove_datetime_columns", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "task",
        sa.Column(
            "remove_constant_columns", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "task",
        sa.Column(
            "find_continous_columns", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "task",
        sa.Column(
            "create_dummy_columns",
            sa.VARCHAR(length=1000),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "task",
        sa.Column(
            "remove_duplicate_columns", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("task", "task_params")
    # ### end Alembic commands ###
