"""empty message

Revision ID: 7235437ec25f
Revises: b1b805b56381
Create Date: 2019-05-24 21:54:02.492009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7235437ec25f"
down_revision = "b1b805b56381"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feature_store",
        sa.Column("stored_features", sa.String(length=10000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feature_store", "stored_features")
    # ### end Alembic commands ###
