"""empty message

Revision ID: 72537deb7b2b
Revises: 153ddab42d1c
Create Date: 2020-04-24 11:57:42.773870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "72537deb7b2b"
down_revision = "153ddab42d1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_instance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.Column("project_status", sa.Integer(), nullable=True),
        sa.Column("design_metadata", sa.String(length=100000), nullable=True),
        sa.Column("artifact_metadata", sa.String(length=100000), nullable=True),
        sa.Column("blueprint", sa.String(length=100000), nullable=True),
        sa.Column("assignee", sa.Integer(), nullable=True),
        sa.Column("reviewer", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignee"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_instance")
    # ### end Alembic commands ###
