"""empty message

Revision ID: 73195e2992b8
Revises: 356fccf09646
Create Date: 2023-06-02 11:34:25.738218

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "73195e2992b8"
down_revision = "356fccf09646"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("nac_roles_name_key", "nac_roles", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("nac_roles_name_key", "nac_roles", ["name"])
    # ### end Alembic commands ###
