"""empty message

Revision ID: 757c33783eb9
Revises: 30fbaaaf5426
Create Date: 2020-04-02 20:26:50.394877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "757c33783eb9"
down_revision = "30fbaaaf5426"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("artifact_metadata", sa.String(length=100000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "artifact_metadata")
    # ### end Alembic commands ###
