"""empty message

Revision ID: 75c0dcb40473
Revises: 50790be30c81
Create Date: 2020-05-19 09:23:59.456296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75c0dcb40473"
down_revision = "50790be30c81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "widget_group", sa.Column("code", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("widget_group", "code")
    # ### end Alembic commands ###
