"""empty message

Revision ID: 7c93f3cb866f
Revises: c01b4542bab7
Create Date: 2020-01-15 09:26:40.243939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7c93f3cb866f"
down_revision = "c01b4542bab7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dashboard_widget", "widget_data")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dashboard_widget",
        sa.Column(
            "widget_data", sa.VARCHAR(length=100000), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
