"""empty message

Revision ID: 803f6c097c65
Revises: 177598c0bd81
Create Date: 2022-09-12 12:35:24.422531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "803f6c097c65"
down_revision = "177598c0bd81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("last_logout", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("user", sa.Column("failed_login_count", sa.Integer(), nullable=True))
    op.add_column(
        "user", sa.Column("failed_login_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "failed_login_at")
    op.drop_column("user", "failed_login_count")
    op.drop_column("user", "last_logout")
    # ### end Alembic commands ###
