"""empty message

Revision ID: 8343d2d7e921
Revises: 8343d2d7e920
Create Date: 2020-06-10 15:22:10.810085

"""
from alembic import op
import sqlalchemy as sa
import json

# revision identifiers, used by Alembic.
revision = "8343d2d7e921"
down_revision = "8343d2d7e920"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    widgets = conn.execute("SELECT id, test_code_params FROM widget").fetchall()

    print(
        "CODEX >>> WIDGET FACTORY | Migrating test_code for widgets to codex-integration branch."
    )

    widget_updates = 0
    total_widgets = 0

    for widget in widgets:
        if widget.test_code_params and widget.test_code_params != "":
            testcode_data = {}
            testcode_data = json.loads(widget.test_code_params)

            testcode_data["branch"] = "codex-integration".strip()
            testcode_data["repo"] = "codex-widget-factory".strip()
            testcode_data["path"] = testcode_data["path"].strip()

            conn.execute(
                sa.sql.text(
                    "UPDATE widget SET test_code_params = :testcode_json WHERE id = :widget_id"
                ),
                testcode_json=json.dumps(testcode_data),
                widget_id=widget.id,
            )
            widget_updates += 1

        print(".", end="")
        total_widgets += 1

    print("")
    print(
        f"CODEX >>> WIDGET FACTORY | Migrating widget test_code >> Total widgets: {total_widgets} >> Updated widgets: {widget_updates}"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('project', 'industry')
    pass
    # ### end Alembic commands ###
