"""empty message

Revision ID: 854f2d945c07
Revises: 76b5447ca329
Create Date: 2022-02-10 12:09:36.306106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "854f2d945c07"
down_revision = "76b5447ca329"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("account", sa.String(length=200), nullable=True))
    op.add_column("project", sa.Column("definition_content", sa.Text(), nullable=True))
    op.add_column(
        "project", sa.Column("problem_area", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "problem_area")
    op.drop_column("project", "definition_content")
    op.drop_column("project", "account")
    # ### end Alembic commands ###
