"""empty message

Revision ID: 8819d9a8341f
Revises: 14a0364ae340
Create Date: 2022-03-16 16:29:07.394152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8819d9a8341f"
down_revision = "1a91d3ff3f2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_notebook_config", sa.Column("blueprint", sa.Text(), nullable=True)
    )
    op.add_column(
        "project_notebook_config", sa.Column("exec_logs", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_notebook_config", "exec_logs")
    op.drop_column("project_notebook_config", "blueprint")
    # ### end Alembic commands ###
