"""empty message

Revision ID: 8ff47563040a
Revises: 1ecf2811af73
Create Date: 2020-01-04 17:13:46.954954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ff47563040a"
down_revision = "1ecf2811af73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column("data_dashboard_saved_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "data_dashboard_saved_at")
    # ### end Alembic commands ###
