"""empty message

Revision ID: 9df4fe52df9a
Revises: 8819d9a8341f
Create Date: 2022-03-16 16:40:04.132619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9df4fe52df9a"
down_revision = "8819d9a8341f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_notebook_config",
        sa.Column("name", sa.String(length=256), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_notebook_config", "name")
    # ### end Alembic commands ###
