"""empty message

Revision ID: a11cd47d64cb
Revises: a11cd47d64ca
Create Date: 2020-06-10 15:22:10.810085

"""
from alembic import op
import sqlalchemy as sa
import json

# revision identifiers, used by Alembic.
revision = "a11cd47d64cb"
down_revision = "a11cd47d64ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    widgets = conn.execute("SELECT id, test_code_params FROM widget").fetchall()

    print(
        "CODEX >>> WIDGET FACTORY | Migrating test_code for widgets to codex-integration branch."
    )

    widget_updates = 0
    total_widgets = 0

    for widget in widgets:
        if widget.test_code_params and widget.test_code_params != "":
            testcode_data = {}
            testcode_data = json.loads(widget.test_code_params)

            testcode_data["path"] = testcode_data["path"].replace(
                "codex-widget-factory", "codex_widget_factory", 1
            )

            conn.execute(
                sa.sql.text(
                    "UPDATE widget SET test_code_params = :testcode_json WHERE id = :widget_id"
                ),
                testcode_json=json.dumps(testcode_data),
                widget_id=widget.id,
            )
            widget_updates += 1

        print(".", end="")
        total_widgets += 1

    print("")
    print(
        f"CODEX >>> WIDGET FACTORY | Migrating widget test_code >> Total widgets: {total_widgets} >> Updated widgets: {widget_updates}"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('project', 'industry')
    pass
    # ### end Alembic commands ###
