"""empty message

Revision ID: a7b919dd953a
Revises: dcdc3c49a590
Create Date: 2019-05-10 14:43:17.881428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a7b919dd953a"
down_revision = "dcdc3c49a590"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_set", sa.Column("task_execution_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "data_set", "task_execution", ["task_execution_id"], ["id"]
    )
    op.add_column("task", sa.Column("data_set_id", sa.Integer(), nullable=True))
    op.add_column("task", sa.Column("data_source_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "task", "data_set", ["data_set_id"], ["id"])
    op.create_foreign_key(None, "task", "data_source", ["data_source_id"], ["id"])
    op.add_column("task_execution", sa.Column("task_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "task_execution", "task", ["task_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task_execution", type_="foreignkey")
    op.drop_column("task_execution", "task_id")
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_column("task", "data_source_id")
    op.drop_column("task", "data_set_id")
    op.drop_constraint(None, "data_set", type_="foreignkey")
    op.drop_column("data_set", "task_execution_id")
    # ### end Alembic commands ###
