"""empty message

Revision ID: b1b805b56381
Revises: f54b23fbdb1d
Create Date: 2019-05-24 21:29:20.649511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1b805b56381"
down_revision = "f54b23fbdb1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feature_store", sa.Column("data_set_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "feature_store", "data_set", ["data_set_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feature_store", type_="foreignkey")
    op.drop_column("feature_store", "data_set_id")
    # ### end Alembic commands ###
