"""empty message

Revision ID: b67161383242
Revises: 0ee78986076a
Create Date: 2020-01-11 15:31:44.684511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b67161383242"
down_revision = "0ee78986076a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("project_type", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "project_type")
    # ### end Alembic commands ###
