"""empty message

Revision ID: b78bb81d7ebc
Revises: 8d06d7b7151a
Create Date: 2021-06-03 12:29:47.474162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b78bb81d7ebc"
down_revision = "8d06d7b7151a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("hashed_password", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
