"""empty message

Revision ID: bb74a5b241b0
Revises: 55cb5621f9d0
Create Date: 2020-04-30 12:05:53.163072

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "bb74a5b241b0"
down_revision = "55cb5621f9d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE public.project ALTER COLUMN design_metadata TYPE TEXT, ALTER COLUMN artifact_metadata TYPE TEXT, ALTER COLUMN blueprint TYPE TEXT;"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.alter_column('project', 'design_metadata', sa.String(length=100000))
    # op.alter_column('project', 'artifact_metadata', sa.String(length=100000))
    # op.alter_column('project', 'blueprint', sa.String(length=100000))
    # ### end Alembic commands ###
