"""empty message

Revision ID: bfdeb679ba82
Revises: 7b262ab23a55
Create Date: 2019-05-25 15:54:55.522280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bfdeb679ba82"
down_revision = "7b262ab23a55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("task_data", sa.String(length=1000000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "task_data")
    # ### end Alembic commands ###
