"""empty message

Revision ID: c01b4542bab7
Revises: b67161383242
Create Date: 2020-01-14 20:44:51.253653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c01b4542bab7"
down_revision = "b67161383242"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_widget",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_execution_id", sa.Integer(), nullable=True),
        sa.Column("widget_type", sa.String(length=100), nullable=True),
        sa.Column("widget_params", sa.String(length=10000), nullable=True),
        sa.Column("widget_data", sa.String(length=100000), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_execution_id"],
            ["task_execution.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dashboard_widget")
    # ### end Alembic commands ###
