"""empty message

Revision ID: c73ce69a1aa8
Revises: 32515aa20f8a
Create Date: 2019-05-18 18:56:31.539495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c73ce69a1aa8"
down_revision = "32515aa20f8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feature", sa.Column("univariate_json", sa.String(length=100000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feature", "univariate_json")
    # ### end Alembic commands ###
