"""empty message

Revision ID: ca12ebd1d57d
Revises: bfdeb679ba82
Create Date: 2019-05-25 16:11:34.565205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca12ebd1d57d"
down_revision = "bfdeb679ba82"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "task_data")
    op.add_column(
        "task_execution",
        sa.Column("task_execution_data", sa.String(length=1000000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_execution", "task_execution_data")
    op.add_column(
        "task",
        sa.Column(
            "task_data", sa.VARCHAR(length=1000000), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
