"""empty message

Revision ID: d20517bb29bc
Revises: a3962b2e1040
Create Date: 2019-05-11 15:51:49.697516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d20517bb29bc"
down_revision = "a3962b2e1040"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("model_train_task_id", sa.Integer(), nullable=True))
    op.drop_constraint("task_task_id_fkey", "task", type_="foreignkey")
    op.create_foreign_key(None, "task", "task", ["model_train_task_id"], ["id"])
    op.drop_column("task", "task_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("task_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "task", type_="foreignkey")
    op.create_foreign_key("task_task_id_fkey", "task", "task", ["task_id"], ["id"])
    op.drop_column("task", "model_train_task_id")
    # ### end Alembic commands ###
