"""empty message

Revision ID: d8ecc0fc5e37
Revises: d8ecc0fc5e36
Create Date: 2020-07-23 16:25:09.990114

"""
from alembic import op
import sqlalchemy as sa
import json


# revision identifiers, used by Alembic.
revision = "d8ecc0fc5e37"
down_revision = "d8ecc0fc5e36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    conn = op.get_bind()
    project_nb_configs = conn.execute(
        "SELECT id, config_params FROM project_notebook_config"
    ).fetchall()

    print("CODEX >>> PROJECT NOTEBOOK CONFIGURATIONS | Migrating config", end="")

    updated_count = 0

    for project_nb_config in project_nb_configs:
        if project_nb_config.config_params is not None:
            # print(f"Params for ID-{project_nb_config.id} : {project_nb_config.config_params}")
            config_params = json.loads(project_nb_config.config_params)
            changed = False
            for widget_param in config_params["widgets"]:
                if widget_param["component_name"] == "get_ingested_df":
                    widget_param["component_name"] = "get_ingested_data"
                    widget_param["alias_name"] = widget_param["alias_name"].replace(
                        "get_ingested_df", "get_ingested_data"
                    )
                    changed = True
                elif widget_param["component_name"] == "get_aggregated_df":
                    widget_param["component_name"] = "get_aggregated_data"
                    widget_param["alias_name"] = widget_param["alias_name"].replace(
                        "get_aggregated_df", "get_aggregated_data"
                    )
                    changed = True
                elif widget_param["component_name"] == "get_transformed_df":
                    widget_param["component_name"] = "get_transformed_data"
                    widget_param["alias_name"] = widget_param["alias_name"].replace(
                        "get_transformed_df", "get_transformed_data"
                    )
                    changed = True

            if changed:
                conn.execute(
                    sa.sql.text(
                        "UPDATE project_notebook_config SET config_params = :config_json WHERE id = :project_nb_config_id"
                    ),
                    config_json=json.dumps(config_params),
                    project_nb_config_id=project_nb_config.id,
                )
                updated_count += 1
                print(".", end="")

    print("")
    print(
        f"CODEX >>> PROJECT NOTEBOOK CONFIGURATIONS | Finished migrating config: {str(updated_count)}"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
