"""empty message

Revision ID: df48d65b169e
Revises: b160f013d6bd
Create Date: 2020-08-27 01:21:41.287847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df48d65b169e"
down_revision = "b160f013d6bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_config", sa.Column("deployed_app_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "app_config",
        sa.Column("last_deployed_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_config", "last_deployed_at")
    op.drop_column("app_config", "deployed_app_id")
    # ### end Alembic commands ###
