initial_infra_type_seed = {
    "name": "k8",
    "cloud_provider_id": 1,
}

initial_llm_cloud_provider_seed = {
    "name": "Azure",
    "is_active": True,
}

initial_compute_service_seed = [
    {"name": "AKS", "compute_type": "CPU", "cloud_provider_id": 1, "is_active": True},
    {"name": "App service", "compute_type": "CPU", "cloud_provider_id": 1, "is_active": True},
]

initial_llm_compute_config = [
    {
        "sku": "NC4as_T4_v3",
        "vcpu": 4,
        "is_active": True,
        "type": "GPU",
        "ram": 28,
        "storage_size": "180",
        "iops": 24480,
        "cloud_provider_id": 1,
        "estimated_cost": 0.75,
        "data_disks": 8,
        "compute_type": None,
        "compute_service_id": 1,
    },
    {
        "sku": "Standard_NC24ads_A100_v424",
        "vcpu": 24,
        "is_active": True,
        "type": "GPU",
        "ram": 220,
        "storage_size": "960",
        "iops": 30000,
        "cloud_provider_id": 1,
        "estimated_cost": 3.4,
        "data_disks": 8,
        "compute_type": None,
        "compute_service_id": 1,
    },
    {
        "sku": "Standard_B4ms",
        "vcpu": 4,
        "is_active": True,
        "type": "CPU",
        "ram": 16,
        "storage_size": "32",
        "iops": 2880,
        "cloud_provider_id": 1,
        "estimated_cost": 121.0,
        "data_disks": 8,
        "compute_type": None,
        "compute_service_id": 1,
    },
    {
        "sku": "Standard_A4m_v2",
        "vcpu": 4,
        "is_active": True,
        "type": "CPU",
        "ram": 32,
        "storage_size": "40",
        "iops": 6400,
        "cloud_provider_id": 1,
        "estimated_cost": 173.0,
        "data_disks": 8,
        "compute_type": None,
        "compute_service_id": 1,
    },
    {
        "sku": "PremiumV3_P0V3",
        "vcpu": 1,
        "is_active": True,
        "type": None,
        "ram": 4,
        "storage_size": "250",
        "iops": None,
        "cloud_provider_id": 1,
        "estimated_cost": None,
        "data_disks": None,
        "compute_type": None,
        "compute_service_id": 2,
    },
    {
        "sku": "PremiumV3_P1V3",
        "vcpu": 2,
        "is_active": True,
        "type": None,
        "ram": 8,
        "storage_size": "250",
        "iops": None,
        "cloud_provider_id": 1,
        "estimated_cost": None,
        "data_disks": None,
        "compute_type": None,
        "compute_service_id": 2,
    },
    {
        "sku": "PremiumV3_P2V3",
        "vcpu": 4,
        "is_active": True,
        "type": None,
        "ram": 16,
        "storage_size": "250",
        "iops": None,
        "cloud_provider_id": 1,
        "estimated_cost": None,
        "data_disks": None,
        "compute_type": None,
        "compute_service_id": 2,
    },
    {
        "sku": "PremiumV3_P3V3",
        "vcpu": 8,
        "is_active": True,
        "type": None,
        "ram": 32,
        "storage_size": "250",
        "iops": None,
        "cloud_provider_id": 1,
        "estimated_cost": None,
        "data_disks": None,
        "compute_type": None,
        "compute_service_id": 2,
    },
]
