summary: "Update alert notif"
tags:
  - product/Alerts
description: "Updates the alert notif data for the given alert ID"
produces:
- "application/json"
security:
  - Authorization: []

parameters:
- in: "path"
  name: "alertId"
  required: "true"
  description: "The alert ID for which the data has to be updated"
  schema:
    type: "integer"

requestBody:
  required: true
  content:
    application/json:
      schema:
        required: [receive_notification]
        properties:
          receive_notification:
            type: "boolean"
        example: {"receive_notification": true}

responses:
  200:
    description: "Return successful update message"
    schema:
      type: "object"
    example: {"message": "Updated Successfully"}
  500:
    description: "Error while updating notification for alert"