apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.hub.extraEnv.clusterRoleBindingName }}
subjects:
- kind: ServiceAccount
  name: hub
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: {{ .Values.hub.extraEnv.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io