summary: "Create Dynamic Execution environment"
tags:
  - product/DynamicExecutionEnvironment
description: "Create Execution environment on the platform utils execution environment module"
consumes:
- application/json
produces:
- application/json
security:
  - Authorization: []

requestBody:
  required: true
  content:
    application/json:
      schema:
        required: [name, requirements, py_version]
        properties:
          name:
            type: string
          requirements:
            type: string
          py_version:
            type: string
        example: {'name': "Execution Env1", 'requirements': "package1\npackage2", 'py_version': "3.9.2"}

responses:
  200:
    description: "API successful"
    schema:
      type: object
  500:
    description: "Error"
    schema:
      type: object
    example: {'status': 'error', 'error': 'Error creating execution environment'}

