summary: "Update App Dynamic Execution environment"
tags:
  - product/DynamicExecutionEnvironment
description: "Update Execution environment for the given id"
produces:
- application/json
security:
  - Authorization: []

requestBody:
  required: true
  content:
    application/json:
      schema:
        required: [app_id, exec_env_id]
        properties:
          app_id:
            type: integer
          exec_env_id:
            type: integer
        example: {'app_id': 1, 'exec_env_id': 1}

responses:
  200:
    description: "API successful"
    schema:
      type: object
  404:
    description: "ID not found"
    schema:
      type: object
    example: {'status': 'error', 'error': 'item not found'}
  500:
    description: "Error"
    schema:
      type: object
    example: {'status': 'error', 'error': 'Error updating app dynamic execution environment'}