import React from 'react';
import { render, screen, cleanup } from '@testing-library/react';
import { Router } from 'react-router-dom';
import { createMemoryHistory } from 'history';
import AppDashboard from '../../components/AppDashboard';
import CustomThemeContextProvider from '../../themes/customThemeContext';

const history = createMemoryHistory();

describe('Codex Product test', () => {
    afterEach(cleanup);

    test('Should render AppAdmin Component', () => {
        const app_info = {
            id: 26,
            name: 'Integrated Demand Forecasting',
            theme: 'blue',
            screens: [
                {
                    id: 128,
                    screen_index: 27,
                    screen_name: 'Growth Lever Simulation',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: 'review',
                    level: null,
                    graph_type: null,
                    horizontal: null,
                    rating_url: 'https://www.google.com/',
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 131,
                    screen_index: 30,
                    screen_name: 'Goal Oriented Simulation',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: 'review',
                    level: 1,
                    graph_type: null,
                    horizontal: null,
                    rating_url: 'https://www.themathcompany.com/',
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 101,
                    screen_index: 0,
                    screen_name: 'Demand Analysis',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: 'review',
                    level: null,
                    graph_type: null,
                    horizontal: null,
                    rating_url: 'https://www.google.com/',
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 102,
                    screen_index: 1,
                    screen_name: 'Size & Opportunity',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 103,
                    screen_index: 2,
                    screen_name: 'Demand Sizing',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '2-1',
                    horizontal: null,
                    rating_url: null,
                    widget_count: 7,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 104,
                    screen_index: 3,
                    screen_name: 'Opportunity Breakdown',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 5,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 105,
                    screen_index: 4,
                    screen_name: 'Pattern Analysis',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 106,
                    screen_index: 5,
                    screen_name: 'Characteristics',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 3,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 107,
                    screen_index: 6,
                    screen_name: 'Portfolio Segmentation',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 4,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 108,
                    screen_index: 7,
                    screen_name: 'Exception Analysis',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 1,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 109,
                    screen_index: 8,
                    screen_name: 'Velocity',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 4,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 110,
                    screen_index: 9,
                    screen_name: 'Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: null,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 111,
                    screen_index: 10,
                    screen_name: 'Industry',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 112,
                    screen_index: 11,
                    screen_name: 'Baseline Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 7,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 113,
                    screen_index: 12,
                    screen_name: 'Driver (Leading Indicator) Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 3,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 114,
                    screen_index: 13,
                    screen_name: 'Impact Analysis',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 3,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 115,
                    screen_index: 14,
                    screen_name: 'Driver Interactions',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 116,
                    screen_index: 15,
                    screen_name: 'Category',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 117,
                    screen_index: 16,
                    screen_name: 'Baseline Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 7,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 118,
                    screen_index: 17,
                    screen_name: 'Driver (Leading Indicator) Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 3,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 119,
                    screen_index: 18,
                    screen_name: 'Impact Analysis',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 3,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 120,
                    screen_index: 19,
                    screen_name: 'Driver Interactions',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 121,
                    screen_index: 20,
                    screen_name: 'SKU',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 122,
                    screen_index: 21,
                    screen_name: 'Baseline Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 7,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 123,
                    screen_index: 22,
                    screen_name: 'Driver (Leading Indicator) Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-1',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 2,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 124,
                    screen_index: 23,
                    screen_name: 'Impact Analysis',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 3,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 125,
                    screen_index: 24,
                    screen_name: 'Driver Interactions',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 126,
                    screen_index: 25,
                    screen_name: 'Collaborative Planning',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: null,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 127,
                    screen_index: 26,
                    screen_name: 'Business Planning Support',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: '1-1',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 6,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 129,
                    screen_index: 28,
                    screen_name: 'Build Scenario',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: '1-1',
                    horizontal: true,
                    rating_url: 'https://www.google.com/',
                    widget_count: 6,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 130,
                    screen_index: 29,
                    screen_name: 'Compare Scenarios',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: '3-1',
                    horizontal: true,
                    rating_url: '',
                    widget_count: 4,
                    screen_filters_values: false,
                    action_settings: false
                }
            ],
            modules: {
                dashboard: true,
                filter_settings: {
                    Brand: {
                        enabled: true,
                        exclude: [],
                        include: '',
                        label: 'Brand',
                        parent: 'Sub Category'
                    },
                    Category: {
                        enabled: true,
                        exclude: [],
                        include: '',
                        label: 'Category',
                        parent: 'Industry'
                    },
                    Industry: {
                        enabled: true,
                        exclude: [],
                        include: '',
                        label: 'Industry',
                        parent: 'Region'
                    },
                    Region: {
                        enabled: true,
                        exclude: [],
                        include: '',
                        label: 'Region',
                        parent: 'Time Frame'
                    },
                    'Sub Category': {
                        enabled: true,
                        exclude: [],
                        include: '',
                        label: 'Sub Category',
                        parent: 'Category'
                    },
                    'Time Frame': {
                        enabled: true,
                        exclude: [],
                        include: '',
                        label: 'Time Frame',
                        parent: ''
                    }
                },
                filters: true,
                user_mgmt: false,
                data_story: true,
                minerva: { enabled: true, tenent_id: 'cpg' }
            },
            industry: 'CPG',
            function: 'Supply Chain',
            description: 'Forecast demand and potential growth opportunity',
            blueprint_link: '/projects/2/design',
            config_link: '/projects/2/case-studies/78/notebooks/101/app-configs/10/edit',
            approach_url:
                'https://themathcompany-my.sharepoint.com/:w:/p/deepika_k/ERq3u7rX5FxGuQUtVm3HAwsB8QP8aoCinrZN6SDiUjLxvw',
            logo_url: false,
            small_logo_url: false,
            story_count: 8,
            restricted_app: false,
            is_user_admin: true,
            permissions: false
        };

        const props = {
            history: history,
            location: {
                hash: '',
                key: '3154u2',
                pathname: '/app/26/dashboard',
                search: ''
            },
            match: {
                isExact: true,
                params: { app_id: '26' },
                path: '/app/:app_id/dashboard',
                url: '/app/26/dashboard'
            }
        };
        const routes = [
            {
                collapsed: true,
                expanded: false,
                href: '/app/26/demand-analysis/size-opportunity/demand-sizing',
                original_href: '/app/26/demand-analysis',
                screen_item: {
                    action_settings: false,
                    graph_type: null,
                    horizontal: null,
                    id: 101,
                    level: null,
                    rating_url: 'https://www.google.com/',
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: 'review',
                    screen_index: 0,
                    screen_name: 'Demand Analysis',
                    widget_count: 0
                },
                selected: false,
                show: true,
                show_title: false
            },
            {
                href: '/app/26/demand-analysis/size-opportunity/demand-sizing',
                level: 1,
                original_href: '/app/26/demand-analysis/size-opportunity',
                screen_item: {
                    action_settings: false,
                    graph_type: null,
                    horizontal: null,
                    id: 102,
                    level: 1,
                    rating_url: null,
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: null,
                    screen_index: 1,
                    screen_name: 'Size & Opportunity',
                    widget_count: 0
                },
                selected: false,
                show: false,
                show_title: false
            },
            {
                href: '/app/26/demand-analysis/size-opportunity/demand-sizing',
                level: 2,
                original_href: '/app/26/demand-analysis/size-opportunity/demand-sizing',
                screen_item: {
                    action_settings: false,
                    graph_type: '2-1',
                    horizontal: null,
                    id: 103,
                    level: 2,
                    rating_url: '',
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: null,
                    screen_index: 2,
                    screen_name: 'Demand Sizing',
                    widget_count: 7
                },
                selected: false,
                show: false,
                show_title: true
            },
            {
                collapsed: true,
                expanded: false,
                href: '/app/26/forecast/industry/baseline-forecast',
                original_href: '/app/26/forecast',
                screen_item: {
                    action_settings: false,
                    graph_type: null,
                    horizontal: null,
                    id: 110,
                    level: null,
                    rating_url: null,
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: 'analyze',
                    screen_index: 9,
                    screen_name: 'Forecast',
                    widget_count: 0
                },
                selected: false,
                show: true,
                show_title: false
            },
            {
                href: '/app/26/forecast/sku/baseline-forecast',
                level: 2,
                original_href: '/app/26/forecast/sku/baseline-forecast',
                screen_item: {
                    action_settings: false,
                    graph_type: '1-2',
                    horizontal: true,
                    id: 122,
                    level: 2,
                    rating_url: null,
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: null,
                    screen_index: 21,
                    screen_name: 'Baseline Forecast',
                    widget_count: 7
                },
                selected: false,
                show: false,
                show_title: true
            },
            {
                expanded: false,
                href: '/app/26/growth-lever-simulation/build-scenario',
                original_href: '/app/26/growth-lever-simulation',
                screen_item: {
                    action_settings: false,
                    graph_type: null,
                    horizontal: null,
                    id: 128,
                    level: null,
                    rating_url: 'https://www.google.com/',
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: 'simulate',
                    screen_index: 27,
                    screen_name: 'Growth Lever Simulation',
                    widget_count: 0
                },
                selected: false,
                show: true,
                show_title: false
            },
            {
                href: '/app/26/collaborative-planning/business-planning-support',
                level: 1,
                original_href: '/app/26/collaborative-planning/business-planning-support',
                screen_item: {
                    action_settings: false,
                    graph_type: '1-1',
                    horizontal: true,
                    id: 127,
                    level: 1,
                    rating_url: null,
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: null,
                    screen_index: 26,
                    screen_name: 'Business Planning Support',
                    widget_count: 6
                },
                selected: false,
                show: false,
                show_title: true
            },
            {
                href: '/app/26/growth-lever-simulation/build-scenario',
                level: 1,
                original_href: '/app/26/growth-lever-simulation/build-scenario',
                screen_item: {
                    action_settings: false,
                    graph_type: '1-1',
                    horizontal: true,
                    id: 129,
                    level: 1,
                    rating_url: 'https://www.google.com/',
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: null,
                    screen_index: 28,
                    screen_name: 'Build Scenario',
                    widget_count: 6
                },
                selected: false,
                show: false
            },
            {
                href: '/app/26/growth-lever-simulation/compare-scenarios',
                level: 1,
                original_href: '/app/26/growth-lever-simulation/compare-scenarios',
                screen_item: {
                    action_settings: false,
                    graph_type: '3-1',
                    horizontal: true,
                    id: 130,
                    level: 1,
                    rating_url: '',
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: null,
                    screen_index: 29,
                    screen_name: 'Compare Scenarios',
                    widget_count: 4
                },
                selected: false,
                show: false
            }
        ];
        const { getByText, debug } = render(
            <CustomThemeContextProvider>
                <Router history={history}>
                    <AppDashboard app_info={app_info} routes={routes} {...props} />
                </Router>
            </CustomThemeContextProvider>
        );
    });
    test('Should render AppAdmin1 Component', () => {
        const app_info = {
            id: 26,
            name: 'Integrated Demand Forecasting',
            theme: 'blue',
            screens: [
                {
                    id: 128,
                    screen_index: 27,
                    screen_name: 'Growth Lever Simulation',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: 'review',
                    level: null,
                    graph_type: null,
                    horizontal: null,
                    rating_url: 'https://www.google.com/',
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 131,
                    screen_index: 30,
                    screen_name: 'Goal Oriented Simulation',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: 'review',
                    level: 1,
                    graph_type: null,
                    horizontal: null,
                    rating_url: 'https://www.themathcompany.com/',
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 101,
                    screen_index: 0,
                    screen_name: 'Demand Analysis',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: 'review',
                    level: null,
                    graph_type: null,
                    horizontal: null,
                    rating_url: 'https://www.google.com/',
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 102,
                    screen_index: 1,
                    screen_name: 'Size & Opportunity',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 103,
                    screen_index: 2,
                    screen_name: 'Demand Sizing',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '2-1',
                    horizontal: null,
                    rating_url: null,
                    widget_count: 7,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 104,
                    screen_index: 3,
                    screen_name: 'Opportunity Breakdown',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 5,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 105,
                    screen_index: 4,
                    screen_name: 'Pattern Analysis',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 106,
                    screen_index: 5,
                    screen_name: 'Characteristics',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 3,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 107,
                    screen_index: 6,
                    screen_name: 'Portfolio Segmentation',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 4,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 108,
                    screen_index: 7,
                    screen_name: 'Exception Analysis',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 1,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 109,
                    screen_index: 8,
                    screen_name: 'Velocity',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 4,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 110,
                    screen_index: 9,
                    screen_name: 'Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: null,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 111,
                    screen_index: 10,
                    screen_name: 'Industry',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 112,
                    screen_index: 11,
                    screen_name: 'Baseline Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 7,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 113,
                    screen_index: 12,
                    screen_name: 'Driver (Leading Indicator) Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 3,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 114,
                    screen_index: 13,
                    screen_name: 'Impact Analysis',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 3,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 115,
                    screen_index: 14,
                    screen_name: 'Driver Interactions',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 116,
                    screen_index: 15,
                    screen_name: 'Category',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 117,
                    screen_index: 16,
                    screen_name: 'Baseline Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 7,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 118,
                    screen_index: 17,
                    screen_name: 'Driver (Leading Indicator) Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 3,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 119,
                    screen_index: 18,
                    screen_name: 'Impact Analysis',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 3,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 120,
                    screen_index: 19,
                    screen_name: 'Driver Interactions',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 121,
                    screen_index: 20,
                    screen_name: 'SKU',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 122,
                    screen_index: 21,
                    screen_name: 'Baseline Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 7,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 123,
                    screen_index: 22,
                    screen_name: 'Driver (Leading Indicator) Forecast',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-1',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 2,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 124,
                    screen_index: 23,
                    screen_name: 'Impact Analysis',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: '1-2',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 3,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 125,
                    screen_index: 24,
                    screen_name: 'Driver Interactions',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 2,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 126,
                    screen_index: 25,
                    screen_name: 'Collaborative Planning',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: null,
                    graph_type: null,
                    horizontal: null,
                    rating_url: null,
                    widget_count: 0,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 127,
                    screen_index: 26,
                    screen_name: 'Business Planning Support',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: '1-1',
                    horizontal: true,
                    rating_url: null,
                    widget_count: 6,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 129,
                    screen_index: 28,
                    screen_name: 'Build Scenario',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: '1-1',
                    horizontal: true,
                    rating_url: 'https://www.google.com/',
                    widget_count: 6,
                    screen_filters_values: false,
                    action_settings: false
                },
                {
                    id: 130,
                    screen_index: 29,
                    screen_name: 'Compare Scenarios',
                    screen_description: null,
                    screen_filters_open: null,
                    screen_image: null,
                    level: 1,
                    graph_type: '3-1',
                    horizontal: true,
                    rating_url: '',
                    widget_count: 4,
                    screen_filters_values: false,
                    action_settings: false
                }
            ],
            modules: {
                dashboard: true,
                filter_settings: {
                    Brand: {
                        enabled: true,
                        exclude: [],
                        include: '',
                        label: 'Brand',
                        parent: 'Sub Category'
                    },
                    Category: {
                        enabled: true,
                        exclude: [],
                        include: '',
                        label: 'Category',
                        parent: 'Industry'
                    },
                    Industry: {
                        enabled: true,
                        exclude: [],
                        include: '',
                        label: 'Industry',
                        parent: 'Region'
                    },
                    Region: {
                        enabled: true,
                        exclude: [],
                        include: '',
                        label: 'Region',
                        parent: 'Time Frame'
                    },
                    'Sub Category': {
                        enabled: true,
                        exclude: [],
                        include: '',
                        label: 'Sub Category',
                        parent: 'Category'
                    },
                    'Time Frame': {
                        enabled: true,
                        exclude: [],
                        include: '',
                        label: 'Time Frame',
                        parent: ''
                    }
                },
                filters: true,
                user_mgmt: false,
                data_story: true,
                minerva: { enabled: true, tenent_id: 'cpg' }
            },
            industry: 'CPG',
            function: 'Supply Chain',
            description: 'Forecast demand and potential growth opportunity',
            blueprint_link: '/projects/2/design',
            config_link: '/projects/2/case-studies/78/notebooks/101/app-configs/10/edit',
            approach_url:
                'https://themathcompany-my.sharepoint.com/:w:/p/deepika_k/ERq3u7rX5FxGuQUtVm3HAwsB8QP8aoCinrZN6SDiUjLxvw',
            logo_url: false,
            small_logo_url: false,
            story_count: 8,
            restricted_app: false,
            is_user_admin: true,
            permissions: false
        };

        const props = {
            history: history,
            location: {
                hash: '',
                key: '3154u2',
                pathname: '/app/26/dashboard',
                search: ''
            },
            match: {
                isExact: true,
                params: { app_id: '26' },
                path: '/app/:app_id/dashboard',
                url: '/app/26/dashboard'
            }
        };
        const routes = [
            {
                collapsed: true,
                expanded: false,
                href: '/app/26/demand-analysis/size-opportunity/demand-sizing',
                original_href: '/app/26/demand-analysis',
                screen_item: {
                    action_settings: false,
                    graph_type: null,
                    horizontal: null,
                    id: 101,
                    level: null,
                    rating_url: 'https://www.google.com/',
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: 'random',
                    screen_index: 0,
                    screen_name: 'Demand Analysis',
                    widget_count: 0
                },
                selected: false,
                show: true,
                show_title: false
            },
            {
                href: '/app/26/demand-analysis/size-opportunity/demand-sizing',
                level: 1,
                original_href: '/app/26/demand-analysis/size-opportunity',
                screen_item: {
                    action_settings: false,
                    graph_type: null,
                    horizontal: null,
                    id: 102,
                    level: 1,
                    rating_url: null,
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: null,
                    screen_index: 1,
                    screen_name: 'Size & Opportunity',
                    widget_count: 0
                },
                selected: false,
                show: false,
                show_title: false
            },
            {
                href: '/app/26/demand-analysis/size-opportunity/demand-sizing',
                level: 2,
                original_href: '/app/26/demand-analysis/size-opportunity/demand-sizing',
                screen_item: {
                    action_settings: false,
                    graph_type: '2-1',
                    horizontal: null,
                    id: 103,
                    level: 2,
                    rating_url: '',
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: null,
                    screen_index: 2,
                    screen_name: 'Demand Sizing',
                    widget_count: 7
                },
                selected: false,
                show: false,
                show_title: true
            },
            {
                collapsed: true,
                expanded: false,
                href: '/app/26/forecast/industry/baseline-forecast',
                original_href: '/app/26/forecast',
                screen_item: {
                    action_settings: false,
                    graph_type: null,
                    horizontal: null,
                    id: 110,
                    level: null,
                    rating_url: null,
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_index: 9,
                    screen_name: 'Forecast',
                    widget_count: 0
                },
                selected: false,
                show: true,
                show_title: false
            },
            {
                href: '/app/26/forecast/sku/baseline-forecast',
                level: 2,
                original_href: '/app/26/forecast/sku/baseline-forecast',
                screen_item: {
                    action_settings: false,
                    graph_type: '1-2',
                    horizontal: true,
                    id: 122,
                    level: 2,
                    rating_url: null,
                    screen_auto_refresh: null,
                    screen_description: null,
                    screen_filters_open: null,
                    screen_filters_values: false,
                    screen_image: null,
                    screen_index: 21,
                    screen_name: 'Baseline Forecast',
                    widget_count: 7
                },
                selected: false,
                show: false,
                show_title: true
            }
        ];
        const { getByText, debug } = render(
            <CustomThemeContextProvider>
                <Router history={history}>
                    <AppDashboard app_info={app_info} routes={routes} {...props} />
                </Router>
            </CustomThemeContextProvider>
        );
    });
});
