"""empty message

Revision ID: 9563ca105ee6
Revises: 0edee58fa3dc
Create Date: 2023-01-14 13:44:05.913663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9563ca105ee6"
down_revision = "0edee58fa3dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM app_mapping")
    op.create_table(
        "app_container",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("problem_area", sa.Text(), nullable=True),
        sa.Column("problem", sa.Text(), nullable=True),
        sa.Column("blueprint_link", sa.Text(), nullable=True),
        sa.Column("approach_blob_name", sa.Text(), nullable=True),
        sa.Column("orderby", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("app", sa.Column("parent_container_id", sa.Integer(), nullable=True))
    op.add_column("app", sa.Column("industry", sa.Text(), nullable=True))
    op.add_column("app", sa.Column("function", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_app_parent_container_id"), "app", ["parent_container_id"], unique=False
    )
    op.create_foreign_key(None, "app", "app_container", ["parent_container_id"], ["id"])
    op.drop_constraint("app_mapping_app_id_fkey", "app_mapping", type_="foreignkey")
    op.create_foreign_key(None, "app_mapping", "app_container", ["app_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("app_mapping_app_id_fkey", "app_mapping", type_="foreignkey")
    op.create_foreign_key(
        "app_mapping_app_id_fkey", "app_mapping", "app", ["app_id"], ["id"]
    )
    op.drop_constraint("app_parent_container_id_fkey", "app", type_="foreignkey")
    op.drop_index(op.f("ix_app_parent_container_id"), table_name="app")
    op.drop_column("app", "function")
    op.drop_column("app", "industry")
    op.drop_column("app", "parent_container_id")
    op.drop_table("app_container")
    # ### end Alembic commands ###
