summary: "Create User Role"
tags:
  - product/AppAdmin
description: "Creates App User Role"
produces:
- "application/json"
security:
  - Authorization: []

requestBody:
  description: Details to create the app user role
  required: true
  content:
    application/json:
      schema:
        required: [name, app_id, permissions]
        properties:
          name:
            type: "string"
          app_id:
            type: "integer"
          permissions:
            type: "array"
            items:
              type: "string"
        example: {"name": "test-role", "app_id": 1, "permissions": ["P1", "P2"]}

responses:
  200:
    description: "Created successfully"
    schema:
      type: "object"
  409:
    description: "Already exists"
    schema:
      type: "object"
      example: {'error': 'Role name is conflicting.'}

  422:
    description: "Error while creating"
    schema:
      type: "object"
      example: {'error': "Error in creating app user roles"}
  500:
    description: "Error while creating"
    schema :
      type: "object"