summary: "Update app user responsibilties"
tags:
  - product/AppAdmin
description: "Updates the responsibiltiies for the app user when the existing responsibilties gets updated"
produces:
- "application/json"
security:
  - Authorization: []

parameters:
- in: "path"
  name: "app_id"
  required: "true"
  schema:
    type: "integer"

requestBody:
  description: Details of deleted responsibilties
  required: true
  content:
    application/json:
      schema:
        required: [deleted_responsibilities]
        properties:
          deleted_responsibilities:
            type: "array"
        example: {"deleted_responsibilities": ["resp 1", "resp 2"]}

responses:
  200:
    description: "Updated successfully"
    schema:
      type: "object"
      example: {"message": "Successfully updated the responsibiltiies for app users"}
  422:
    description: "Parsing failed"
    schema:
      type: "object"
      example: {'error': 'Error parsing request data'}
  500:
    description: "Error while updating"
    schema :
      type: "object"
      example:  {'error': 'Error updating the responsibilities for the app user'}