summary: "Update User Role"
tags:
  - product/AppAdmin
description: "Updates App User Role"
produces:
- "application/json"
security:
  - Authorization: []

parameters:
- in: "path"
  name: "app_user_role_id"
  required: "true"
  schema:
    type: "integer"

requestBody:
  description: Details to update the app user role
  required: true
  content:
    application/json:
      schema:
        required: [name, app_id, permissions]
        properties:
          name:
            type: "string"
          app_id:
            type: "integer"
          permissions:
            type: "array"
            items:
              type: "string"
        example: {"name": "test-role", "app_id": 1, "permissions": ["app_screen_user_mgmt", "app_screen_2"]}

responses:
  200:
    description: "Updated successfully"
    schema:
      type: "object"
  404:
    description: "Role Not Found"
    schema:
      type: "object"
      example: {'error': 'item not found'}
  409:
    description: "Already exists"
    schema:
      type: "object"
      example: {'error': 'Role name is conflicting.'}
  422:
    description: "Error while updating"
    schema:
      type: "object"
      example: {'error': "Error in updating app user roles"}
  500:
    description: "Error while updating"
    schema :
      type: "object"
      example:  {'error': 'Error while updating application variable'}