summary: "Get Widget Document"
tags:
  - product/AppAdmin
description: "Get markdown file for a given widget"
produces:
- "application/json"
security:
  - Authorization: []

parameters:
- in: "path"
  name: "md_file_name"
  required: "true"
  schema:
    type: "string"

responses:
  200:
    description: "Request successful"
    schema:
      type: "object"
  500:
    description: "Error"
    schema:
      type: "object"
      example: {'error': 'item not found'}