summary: "Create new NAC user role"
tags:
  - platform/NACUserRoles
description: "This creates a new NAC user role"
consumes:
- "application/json"
produces:
- "application/json"
security:
  - Authorization: []
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: "object"
        properties:
          name:
            type: "string"
            required: "true"
          role_permissions:
            type: "array"
            items:
              type: "number"
              required: true
        example: {
          "name" : "test nac user role",
          "role_permissions" : [1,2]
        }

responses:
  200:
    description: "Success"
    schema:
      type: "object"
      example : {
        "id": 123,
        "name": "user role"
      }

  422:
    description: "Error in query"
    schema:
      type: "object"
      example: {
        "Error": "Error in query operation"
      }


