// const DARK_THEME_BACKGROUND_COLOR='0C2744';
const DARK_THEME_BACKGROUND_COLOR = '#FFFFFF' //0E0617
const DARK_THEME_CUSTOM_BACKGROUND_COLOR = '#FFFFFF'
const DARK_THEME_FONT_COLOR='#220047';
const LIGHT_THEME_FONT_COLOR = '#000000'
const LIGHT_THEME_BACKGROUND_COLOR = '#FFFFFF'
const SUCCESS_COLOR ='#4CAF56';
const DANGER_COLOR ='#D91E18';
const WARNING_COLOR='#FF9800';
const PRIMARY_COLOR='#2196F3';
const COVER_PAGE_OUTLINE='#220047';
module.exports ={
    DARK_THEME_BACKGROUND_COLOR,
    DARK_THEME_CUSTOM_BACKGROUND_COLOR,
    LIGHT_THEME_BACKGROUND_COLOR,
    DARK_THEME_FONT_COLOR,
    SUCCESS_COLOR,
    DANGER_COLOR,
    WARNING_COLOR,
    PRIMARY_COLOR,
    COVER_PAGE_OUTLINE,
    LIGHT_THEME_FONT_COLOR
}