name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: docker/services/product-client/Dockerfile  # Path to frontend Dockerfile
        push: true
        tags: |
          ${{ secrets.AZURE_CONTAINER_REGISTRY }}/danone-xtab-ui-dev:latest

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: docker/productfast.dockerfile  # Path to backend Dockerfile
        push: true
        tags: |
          ${{ secrets.AZURE_CONTAINER_REGISTRY }}/danone-xtab-backend-dev:latest

    - name: Logout from Docker
      run: docker logout ${{ secrets.AZURE_CONTAINER_REGISTRY }}
