"""empty message

Revision ID: 06c489bbecda
Revises: b630c2d36903
Create Date: 2024-03-27 10:26:31.684409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c489bbecda'
down_revision = 'b630c2d36903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_deployment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_deployment_experiment_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('checkpoint_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['llm_experiment_checkpoint.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['llm_deployed_model.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['llm_experiment.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('llm_deployed_model', sa.Column('name', sa.String(length=500), nullable=True))
    op.add_column('llm_deployed_model', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('llm_deployed_model', sa.Column('approval_status', sa.String(length=255), nullable=True))
    op.add_column('llm_deployed_model', sa.Column('deployment_type_id', sa.Integer(), nullable=True))
    op.add_column('llm_deployed_model', sa.Column('progress', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'llm_deployed_model', 'llm_deployment_type', ['deployment_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_deployed_model', type_='foreignkey')
    op.drop_column('llm_deployed_model', 'progress')
    op.drop_column('llm_deployed_model', 'deployment_type_id')
    op.drop_column('llm_deployed_model', 'approval_status')
    op.drop_column('llm_deployed_model', 'description')
    op.drop_column('llm_deployed_model', 'name')
    op.drop_table('llm_deployment_experiment_mapping')
    op.drop_table('llm_deployment_type')
    # ### end Alembic commands ###
