"""empty message

Revision ID: 1453dd17178d
Revises: 84a274163ec0
Create Date: 2021-10-20 01:42:36.551652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1453dd17178d"
down_revision = "84a274163ec0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("story_content", sa.Column("filter_data", sa.Text(), nullable=True))
    op.add_column("story_content", sa.Column("content_json", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("story_content", "content_json")
    op.drop_column("story_content", "filter_data")
    # ### end Alembic commands ###
