"""empty message

Revision ID: 16af0d66bf1d
Revises: 7c7cacea0d92
Create Date: 2024-01-24 17:36:58.829601

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "16af0d66bf1d"
down_revision = "7c7cacea0d92"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE  public.app_theme_mode set bg_variant = 'v3' where deleted_at is null and bg_variant != 'custom'"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE  public.app_theme_mode set bg_variant = 'v2' where deleted_at is null and bg_variant != 'custom'"
    )
    # ### end Alembic commands ###
