"""empty message

Revision ID: 2667055cb410
Revises: 733139013140
Create Date: 2022-03-09 18:24:34.400214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2667055cb410"
down_revision = "733139013140"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts__user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alert_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=100), nullable=True),
        sa.Column("user_email", sa.String(length=100), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("notifications", sa.Column("widget_id", sa.Integer(), nullable=True))
    op.add_column(
        "notifications", sa.Column("title", sa.String(length=100), nullable=True)
    )
    op.add_column("notifications", sa.Column("message", sa.Text(), nullable=True))
    op.add_column("notifications", sa.Column("is_read", sa.Boolean(), nullable=True))
    op.add_column(
        "notifications", sa.Column("user_email", sa.String(length=100), nullable=True)
    )
    op.create_foreign_key(
        None, "notifications", "app_screen_widget", ["widget_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.drop_column("notifications", "user_email")
    op.drop_column("notifications", "is_read")
    op.drop_column("notifications", "message")
    op.drop_column("notifications", "title")
    op.drop_column("notifications", "widget_id")
    op.drop_table("alerts__user")
    # ### end Alembic commands ###
