"""empty message

Revision ID: 28ccb6397ef7
Revises: 25837ba80106
Create Date: 2024-03-15 00:09:46.188896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ccb6397ef7'
down_revision = '25837ba80106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('restricted_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'restricted_access')
    # ### end Alembic commands ###
