"""empty message

Revision ID: 45f2a27f6a65
Revises: 851de3972ac0
Create Date: 2020-10-23 03:03:10.930251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45f2a27f6a65"
down_revision = "851de3972ac0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_screen", sa.Column("level", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_screen", "level")
    # ### end Alembic commands ###
