"""empty message

Revision ID: 476d14d47f86
Revises: 784d45ff14a6
Create Date: 2021-01-14 13:13:03.989850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "476d14d47f86"
down_revision = "784d45ff14a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app", sa.Column("small_logo_blob_name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app", "small_logo_blob_name")
    # ### end Alembic commands ###
