"""empty message

Revision ID: 481b45f38d06
Revises: 8f200fa424f6
Create Date: 2022-01-06 16:31:53.864426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "481b45f38d06"
down_revision = "8f200fa424f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_user", sa.Column("first_name", sa.String(length=1000), nullable=True)
    )
    op.add_column(
        "app_user", sa.Column("last_name", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_user", "last_name")
    op.drop_column("app_user", "first_name")
    # ### end Alembic commands ###
