"""empty message

Revision ID: 4d322939190c
Revises: 2c713fa6f9e9
Create Date: 2021-04-01 02:07:54.067485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d322939190c"
down_revision = "2c713fa6f9e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("story_content", sa.Column("layout_id", sa.Integer(), nullable=True))
    op.drop_constraint(
        "story_content_app_screen_widget_filter_value_id_fkey",
        "story_content",
        type_="foreignkey",
    )
    op.create_foreign_key(None, "story_content", "story_layout", ["layout_id"], ["id"])
    op.drop_column("story_content", "layout_type")
    op.drop_column("story_content", "app_screen_widget_filter_value_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "story_content",
        sa.Column(
            "app_screen_widget_filter_value_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "story_content",
        sa.Column(
            "layout_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "story_content", type_="foreignkey")
    op.create_foreign_key(
        "story_content_app_screen_widget_filter_value_id_fkey",
        "story_content",
        "app_screen_widget_filter_value",
        ["app_screen_widget_filter_value_id"],
        ["id"],
    )
    op.drop_column("story_content", "layout_id")
    # ### end Alembic commands ###
