"""empty message

Revision ID: 5188f964ecad
Revises: 4c2296b47457
Create Date: 2021-05-17 15:06:55.611690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5188f964ecad"
down_revision = "4c2296b47457"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story_share",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("story_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("is_link", sa.Boolean(), nullable=True),
        sa.Column("is_attachment", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["story.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("story_share")
    # ### end Alembic commands ###
