"""empty message

Revision ID: 5d545cfc114a
Revises: 30a2e0b907b0
Create Date: 2022-09-23 14:38:09.545132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5d545cfc114a"
down_revision = "30a2e0b907b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_screen", sa.Column("hidden", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_screen", "hidden")
    # ### end Alembic commands ###


"""
THERE WILL BE A BRANCHING HERE AT THIS MIGRATION VERSION WHEN MERGING WITH DEVELOP.
FOR VERSION 722989f04d4f onwards, which have changes of New App Configurator,
Make sure that you move them all to the tail of the current version of develop and delete this comment afterwards.
"""
