"""empty message

Revision ID: 7c7cacea0d92
Revises: 5ae909d6c398
Create Date: 2024-01-05 13:08:15.755118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7cacea0d92'
down_revision = '5ae909d6c398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_job', sa.Column('result', sa.Text(), nullable=True))
    op.add_column('supported_model', sa.Column('is_finetunable', sa.Boolean(), nullable=True))
    op.add_column('supported_model', sa.Column('config', sa.Text(), nullable=True))
    op.add_column('supported_model', sa.Column('is_submitted', sa.Boolean(), nullable=True))
    op.add_column('supported_model', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('supported_model', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supported_model', 'ended_at')
    op.drop_column('supported_model', 'started_at')
    op.drop_column('supported_model', 'is_submitted')
    op.drop_column('supported_model', 'config')
    op.drop_column('supported_model', 'is_finetunable')
    op.drop_column('model_job', 'result')
    # ### end Alembic commands ###
