"""empty message

Revision ID: 851de3972ac0
Revises: 34c0a9db02d6
Create Date: 2020-10-13 07:41:51.567395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "851de3972ac0"
down_revision = "34c0a9db02d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_screen_widget_value",
        sa.Column("widget_simulated_value", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_screen_widget_value", "widget_simulated_value")
    # ### end Alembic commands ###
