"""empty message

Revision ID: 895be722228c
Revises: 0b8c6721ae48
Create Date: 2020-09-01 00:22:15.796014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "895be722228c"
down_revision = "0b8c6721ae48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_screen_widget", sa.Column("config", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_screen_widget", "config")
    # ### end Alembic commands ###
