"""empty message

Revision ID: 947f792e81b7
Revises: 21ebf373aed6
Create Date: 2024-05-06 12:37:47.147241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947f792e81b7'
down_revision = '21ebf373aed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copilot_tool_version', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('copilot_tool_version_registry_mapping', sa.Column('version', sa.String(length=100), nullable=True))
    op.drop_column('copilot_tool_version_registry_mapping', 'title')
    # To populate version number for existing published tools
    op.execute("""
        WITH version_cte AS (
            SELECT
                ctvrm.tool_version_id,
                ROW_NUMBER() OVER (PARTITION BY ctv.tool_id ORDER BY ctvrm.created_at ASC) - 1 AS version_increment
            FROM
                copilot_tool_version_registry_mapping AS ctvrm
            JOIN
                copilot_tool_version AS ctv ON ctvrm.tool_version_id = ctv.id
            WHERE
                ctvrm.deleted_At IS NULL
                AND ctvrm.deprecated = false
        )
        UPDATE copilot_tool_version_registry_mapping AS ctvrm
        SET version = CONCAT('1.', version_increment, '.0')
        FROM version_cte
        WHERE ctvrm.tool_version_id = version_cte.tool_version_id;
    """)
    # To set existing tool versions verified as false
    op.execute("UPDATE copilot_tool_version SET verified = false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copilot_tool_version_registry_mapping', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('copilot_tool_version_registry_mapping', 'version')
    op.drop_column('copilot_tool_version', 'verified')
    # ### end Alembic commands ###
