"""empty message

Revision ID: 9e4b0009b4e9
Revises: 05bdb1e4d00d
Create Date: 2023-07-20 11:49:43.712221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4b0009b4e9'
down_revision = '05bdb1e4d00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('is_connected_systems_app', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'is_connected_systems_app')
    # ### end Alembic commands ###
