"""empty message

Revision ID: 9f38c274020c
Revises: b59be8060cf4
Create Date: 2020-09-30 01:46:33.066814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f38c274020c"
down_revision = "b59be8060cf4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app", sa.Column("approach_blob_name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app", "approach_blob_name")
    # ### end Alembic commands ###
