"""empty message

Revision ID: a3c5d69f4112
Revises: 49c156f6b116
Create Date: 2021-04-20 21:08:07.128839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a3c5d69f4112"
down_revision = "49c156f6b116"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("story_pages_content_id_fkey", "story_pages", type_="foreignkey")
    op.drop_column("story_pages", "content_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "story_pages",
        sa.Column("content_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "story_pages_content_id_fkey",
        "story_pages",
        "story_content",
        ["content_id"],
        ["id"],
    )
    # ### end Alembic commands ###
