"""empty message

Revision ID: ab333cb8b12e
Revises: 25a550d0084d
Create Date: 2023-08-22 21:41:10.448934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab333cb8b12e'
down_revision = '25a550d0084d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard', sa.Column('dashboard_code', sa.String(length=100), nullable=True, server_default='cpg_rgm'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard', 'dashboard_code')
    # ### end Alembic commands ###
