"""empty message

Revision ID: acc27471591a
Revises: fc463b166dea
Create Date: 2020-08-27 17:17:55.960593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "acc27471591a"
down_revision = "fc463b166dea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_screen_widget_value", sa.Column("widget_value", sa.Text(), nullable=True)
    )
    op.drop_column("app_screen_widget_value", "value")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_screen_widget_value",
        sa.Column("value", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("app_screen_widget_value", "widget_value")
    # ### end Alembic commands ###
