"""empty message

Revision ID: c64dcd46c155
Revises: 0616d4ef4728
Create Date: 2024-02-21 12:05:58.908956

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c64dcd46c155"
down_revision = "0616d4ef4728"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "llm_experiment",
        "test_size",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.add_column(
        "llm_experiment_checkpoint",
        sa.Column("name", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm_experiment_checkpoint", "name")
    op.alter_column(
        "llm_experiment",
        "test_size",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
