"""empty message

Revision ID: ce8b7368bd33
Revises: c64dcd46c155
Create Date: 2024-02-23 16:48:19.497023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8b7368bd33'
down_revision = 'c64dcd46c155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_experiment_setting', sa.Column('save_steps', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_experiment_setting', 'save_steps')
    # ### end Alembic commands ###
