"""empty message

Revision ID: d099dfe3ef9f
Revises: 48fa8873e96f
Create Date: 2024-06-12 15:51:40.991297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd099dfe3ef9f'
down_revision = '48fa8873e96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copilot_conversation', sa.Column('interrupted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copilot_conversation', 'interrupted')
    # ### end Alembic commands ###
