"""empty message

Revision ID: dd3aef88aba1
Revises: 1f1ece569d7e
Create Date: 2022-12-26 11:29:40.184333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd3aef88aba1"
down_revision = "4736d7e22a9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app", sa.Column("variables", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app", "variables")
    # ### end Alembic commands ###
