"""empty message

Revision ID: e06af44e166c
Revises: 9d0b5ae5592e
Create Date: 2023-04-20 19:17:14.593546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e06af44e166c"
down_revision = "9d0b5ae5592e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app", sa.Column("function_defns", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app", "function_defns")
    # ### end Alembic commands ###
