"""empty message

Revision ID: ed0194f5faa4
Revises: ef172feb8796
Create Date: 2024-03-01 14:24:03.819155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0194f5faa4'
down_revision = 'ef172feb8796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_experiment_checkpoint', sa.Column('checkpoint_train_result_path', sa.String(length=255), nullable=True))
    op.add_column('llm_experiment_checkpoint', sa.Column('checkpoint_eval_path', sa.String(length=255), nullable=True))
    op.add_column('llm_experiment_result', sa.Column('checkpoint_log_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_experiment_result', 'checkpoint_log_path')
    op.drop_column('llm_experiment_checkpoint', 'checkpoint_eval_path')
    op.drop_column('llm_experiment_checkpoint', 'checkpoint_train_result_path')
    # ### end Alembic commands ###
